### ISSUE TITLE
Add Index, NoIndex and Follow to page/post settings

### ISSUE THREAD

**Issue by r4g-jon** [PiranhaCMS/piranha.core#1000]
Hello

Here's how to reproduce the problem:

1. Create a new page called "test" in Piranha CMS, add some content and in the "Settings" modal, make sure the checkbox "If the page should be hidden in the sitemap" is checked
2. Go to the /sitemap.xml page
3. You will see the "test" page is in the sitemap

Looking at the code, the sitemap only seems to exclude non-published items but it probably needs to also exclude any items in the Sitemap with "IsHidden = true".

**Comment by r4g-jon** [comment]
I will try to fix this tomorrow.

**Comment by tidyui** [comment]
This is tough one. IsHidden is intended to visually hide an item in the regular navigation. Let’s say you have privacy policy page that you only want to link to in the footer, then you add the page, set it to hidden and then add a link in the footer. This doesn’t mean that you don’t want the content to be indexed.

I get your point, but maybe we need another option for the case you’re describing.

**Comment by r4g-jon** [comment]
It might be worth naming the checkbox option to something like "Hide this page from the navigation" or similar? At least then it's very clear what it does.

Would it be a big job to add in an 'exclude from sitemap.xml' type option?

**Comment by rengert** [comment]
From my point of view, you should manage the robots behavior (index, noindex, follow, ...) and the noindex should have also the effect to hide the page from sitemap and you can set header and meta robots inforamtion. 
That is what i developed for me, and it is working well for me. so i can manage it easily for my pages.

**Comment by saefren** [comment]
@r4g-jon Adding the checkbox would be easy. However, should this setting be inherited by child-pages recursively when generating the sitemap? I would like to have this option (imagine having lots of child-pages). And how about the ability to make an exception on a child-page (which is then again inherited by it's children recursively) ? 

A fairly simple solution would be via the manager GUI, where you can apply the 'IsHiddenFromSitemapXml' setting to all children (recursively). In this case the SitemapMiddleware can stay simple and just check this one 'IsHiddenFromSitemapXml' property. 

Otherwise you're going to have some kind of solution where you maintain inheritance state (which is something Episerver CMS used to have with Dynamic Properties and I found really useful, but alas). 


@rengert should it also do the robots.txt? Because then I'dd like to be able to hook in to the process of generating it's content. For example I currently use a middleware class that can serve different robots-txt files per environment.

**Comment by rengert** [comment]
@saefren what so you mean exactly with "do the robots.txt". from my point of view the only content of robots.txt should be the list of sitemaps. So the flags for index / follow should have effect on:
- sitemap generation
- meat tags in the html header
- http header (optional, but could be a must have, if you would add it to assets as well)

What do you think?

Regarding the automatic generated robots.txt ... i have to use "typo 3" for some projects, there i am using the static file handler to generate the robots.txt as non dynamic route. could be good idea to update the file without doing a deployment.

**Comment by saefren** [comment]
I meant to ask if Piranha should also generate a robots-txt. Because I would like to maintain control over its content.

- **sitemap generation**
  Agreed, however my other questions/remarks regarding inheritance are still open.

- **meta tags in the html head**
  Agreed. Piranha already has meta tags for Keywords/Description (via IMeta which I guess can be extended and I still need to do because I would like to add og:image).
![image](https://user-images.githubusercontent.com/16624717/86809090-c5c8c100-c07b-11ea-9afe-41496d0afe56.png)

- **http header** (optional, but could be a must have, if you would add it to assets as well)
  The X-Robots-Tag? Agreed.

I think Piranha/NetCore is flexible enough that it allows us to integrate these features easily ourselves but they're so common it would be nice to have them available in Piranha.

I had never heard of Typo3 but I also use a static file handler to serve a robots-txt. It's just that I have different robot files depending on the environment (test, staging, non-producton, index nothing!) and I would like to maintain control over the robots-txt.

**Comment by tidyui** [comment]
@saefren og:image will be added as of this issue #1218

**Comment by tidyui** [comment]
@saefren @rengert What are you thinking about for the http headers?

**Comment by rengert** [comment]
@tidyui yes, not sure if it should be handled on folder or / and file level.

**Comment by tidyui** [comment]
As we will start working on this issue I thought I'd write down exactly **what** we will do for the `9.0` release.

## New fields

Pages & Posts will get **three** new fields:

* `MetaIndex` (`true`/`false`, default value `true`)
* `MetaFollow` (`true`/`false`, default value `true`)
* `MetaPriority`(default value `0.5`)

## Behaviour

* **If** `MetaIndex` is set to `false` the page/post will be **excluded** from the built in `Sitemap.xml` generation. 
* The meta-tag `robots` will be added to the extension method `MetaTags()` that can be used for rendering meta-tags from version `8.4`.
* `MetaPriority` will be used when generating `Sitemap.xml` to customize the priority for individual entries.

## How to update/edit

All of these fields will be available in the `SEO` tab in the Page/Post settings in the manager.

## What we won't do

We will not currently look into auto-generating any `robots.txt` files. This will have to be handled by the application.
