### ISSUE TITLE
post base class

### ISSUE THREAD

**Issue by ecnerwal1234** [PiranhaCMS/piranha.core#1087]
The post base class has a field called BlogId. Maybe this should be ArchiveId.  very minor, just thought I would mention something.

**Comment by tidyui** [comment]
`ArchivePages` were initially called `BlogPages` which is why the column is named `BlogId`. When we changed the naming we left the column the way it was as `SQLite` migrations doesn't support changing column names, however since then we've decided that we can't really support 100% backwards compatibility for SQLite and we put migrations for each database in separate projects, so it might change in the future.
