### ISSUE TITLE
Upgrading from 5.2 to 8.1, what do I need to know?

### ISSUE THREAD

**Issue by stamminator** [PiranhaCMS/piranha.core#1088]
I have a mixed site (where some of the routing is controlled by my app and some is controlled by Piranha) using Piranha 5.2.1, .NET Core 2.1, and a SQLite database. I remember that the version 5 update had great Wiki documentation on what needed to change when upgrading, specifically updates to the Startup.cs file. I'm having a tough time figuring out what I need to do this time around for 5 => 8. Could you point me to some documentation or just give me a few pointers? Thanks.

**Comment by tidyui** [comment]
Everything is documented in the Changelog:

https://github.com/PiranhaCMS/piranha.core/wiki/Changelog

Problem here is there’s so many versions. The biggest update by far som to 7.0. If you have any custom blocks or fields you’ll have to rewrite their manager views in VueJs

**Comment by stamminator** [comment]
Thanks, not sure how I missed the changelog. My only question based on what I'm seeing so far is the SQLite breaking change. Does this mean I can't use SQLite going forward, or just that I have to create a new SQLite database and manually migrate existing posts using DML queries?

**Comment by tidyui** [comment]
To begin with you’ll have to create a new database and migrate the data, this is due to the fact that MS has changed the underlying SQLite provider.

Secondly it’s hard for us to guarantee that this won’t ever happen again for SQLite. So far we’ve managed to have full backwards compatibility for SQLite, but this is at the cost that we now have stray columns not used in the database. EF Core hasn’t so far supported any alter statements for SQLite that includes renaming or dropping columns which leaves us rather tied up in what we can do.

Due to all of these things we really don’t recommend SQLite as a production database, even though we try our best to give users the best experience.

**Comment by stamminator** [comment]
10-4. I'll probably spin up a SQL Server 2019 Web edition instance and migrate to that then. Thanks for the info.
