### ISSUE TITLE
Redirecting user during logout

### ISSUE THREAD

**Issue by howardmat** [PiranhaCMS/piranha.core#1198]
I've been working with Piranha for a couple weeks now and just wanted to say you guys are doing an awesome job with it. It's been great to work with. 

I am running into a weird problem when I deploy my application to a server though. When a user clicks Logout from the Manager I want to redirect them to a different page. I have added code to my ISecurity implementation to redirect to a dashboard page. The weird thing is that this works properly when I run the application locally but when I deploy to a server it just redirects to the /manager/login page. 

Here is my ISecurity implementation:

```
public class MyPiranhaAuthenticationService : ISecurity
    {
        /// <summary>
        /// Authenticates the given credentials without
        /// signing in the user.
        /// </summary>
        public bool Authenticate(string username, string password)
        {
            return true;
        }

        /// <summary>
        /// Authenticates and signs in the user with the
        /// given credentials.
        /// </summary>
        public async Task<bool> SignIn(object context, string username, string password)
        {
            return true;
        }

        /// <summary>
        /// Signs out the current user.
        /// </summary>
        public async Task SignOut(object context)
        {
            var response = ((DefaultHttpContext) context).Response;
            response.Redirect("/Dashboard");

            await response.CompleteAsync();
        }
    }
```

I also tried this code in the SignOut method to redirect but the same thing occurs:
```
public Task SignOut(object context)
        {
            var response = ((DefaultHttpContext) context).Response;
            response.Redirect("/Dashboard");

            return response.CompleteAsync();
        }
```

Should I be performing the redirect a different way? 

I know the logout page in Piranha returns a RedirectToPageResult so I was hoping to override that or bypass it.

**Comment by tidyui** [comment]
As the page `Logout.cshtml.cs` performs a redirect right after the call to `SignOut` is performed here:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/Areas/Manager/Pages/Logout.cshtml.cs#L33

My guess is that your local environment handles `CompleteAsync()` differently than when you run the application on `IIS` (or some other production web server). Obviously the production server doesn't seem to end the request after this call is made which makes the second redirect overwrite the first one.

My suggestion is that you put your own version of `Logout.cshtml` (and `Logout.cshtml.cs`) in your application at the same local path, i.e:

    ~/Areas/Manager/Pages/`

and then perform the redirect from your `OnGet` method instead. Your local version of the file should override and be used instead of the one embedded in the manager package.

Best regards

**Comment by howardmat** [comment]
Thank you for the suggestion, it works perfectly.
