### ISSUE TITLE
Slug Length Issue

### ISSUE THREAD

**Issue by eric-wilson** [PiranhaCMS/piranha.core#1201]
Is there a reason why the slug length is limited to 128?  

I'm working on porting a commerce site and they have a ton of url's longer than 128.  I'm trying to figure out if I should implement my own routing & admin section for the e-commerce portion or try to push it into the piranha's manager.  

Other Questions:
Am I taking the right approach?
Is there a best practice/recommendation for this?

If I use piranha's routing then I have a few obstacles: 

My initial thought was to create a custom Piranha.Data.EF and override the HasMaxLength ` mb.Entity<Data.Page>().Property(p => p.Slug).HasMaxLength(128).IsRequired();` 

to something like 1024 <- I know ridiculously big (probably need something closer to 500)

`mb.Entity<Data.Page>().Property(p => p.Slug).HasMaxLength(1024).IsRequired();`

However, the `public abstract class RoutedContentBase` in Core has it set as well, which will most likely throw a validation error (I haven't tested it yet).  

```
[StringLength(128)]
        public string Slug { get; set; }
```
Finally, if I get past all of that, the manager has it hard-coded as too

```
<label>@Localizer.General["Slug"]</label>
<div class="input-group">
    <input v-model="slug" type="text" maxlength="128" class="form-control">
    <div class="input-group-append">
        <div class="input-group-text text-muted">
            {{ piranha.utils.strLength(slug) + "/128" }}
        </div>
    </div>
</div>
```

**Comment by tidyui** [comment]
Hi there! The slug length is set to `128` characters because slugs are meant to be readable URL:s that the user can actually remember 😀 In my opinion `128` character is too long for a good slug as well.

My recommendation is that you don't modify the slug length of Piranha, if you do this you won't be able to update your application when new versions are released. Instead, focus on getting a good new URL-structure and then create Aliases for redirecting the old URL:s to the new ones.

Unfortunately the Alias feature in Piranha has a max length of `256` characters, but this is something we could consider changing. If you think this is a good solution for your use-case, you can open a new issue for this, we might be able to change it for the `8.3` release because it's a quick fix.

**Comment by eric-wilson** [comment]
@tidyui,  Thanks for the explanation but unfortunately that's a show stopper for at least 2 clients of mine.  

If I continue to use the product my only choice will be to fork it and move away from compatibility.  

I get your dislike for slugs greater than 128 but when working e-commerce systems, you'll really need to open it up.  Image a client with over 10,000 products tons of categories and subcategories.  128 doesn't give much wiggle room.  This would be the number one reason you should reconsider it. 

If there's any chance you can reconsider removing the string length in the base component that would be ideal.  I can create a new EF component allowing for larger sizes.  I can even get around the manager piece via a couple of creative ways.

Reasons for doing this:
- Getting others to use the system w/o limitations.  E-commerce systems would be your first roadblock with this limitation.
- It would keep your system open for extensibility: `An open and extendible platform.`
- `The heart and soul of Piranha is about structuring content and editing it in the most intuitive way possible - the rest we leave up to you.` - you could large this includes at 128 slug limit but I would argue that it doesn't.

Anyway, I really like the product so one way or another I'll probably be using it (forking a non-compatible version or ideally referencing the binaries).

Thanks for your consideration!

**Comment by tidyui** [comment]
I totally get your point, and in your use case I understand that you need a longer slug, I only mean that for pages & posts there is little reason for having slugs of this length.

The page & post entities are not build with a product structure in mind, there are several other features you would like for products. At byBrick where I work during the days we have built a custom product module for Piranha which supports several other features like product groups, child products (articles) that are merged with the parent product, special value fields that supports metric/imperial, search indexing, fields and blocks where the editor can select a product to expose as content on a page/post.

I think the question is more than just about slug length. If longer slugs were supported, would really pages/posts and it’s edit views be sufficient to successfully manage this data in the long run?

**Comment by tidyui** [comment]
I have also looked into the possibility in the past to integrate one of the available open source e-commerce systems for .net core with Piranha (like SimplCommerce or NoopCommerce). As these systems are designed to handle products I think this is a much more interesting solution to the problem that we would be very interested to collaborate on!

**Comment by i-love-code** [comment]
I'm also interested in a slim e-commerce implementation with Piranha. I fully intend to try to do this once the "generic content model" changes are in and it's easier to extend Piranha to handle more than just page/post/archive types.

**Comment by eric-wilson** [comment]
@tidyui, 

Thanks for the extra info.  I guess the best solution would be to store my URLs in a different table and add my own middleware to process them.  I was hoping to piggyback off of one routing middleware piece, but this should work fine.

I'm also trying to figure out if I should inject my admin into the manager or simply create it under a different path.... which begs the question on the best way to log into the admin(s).  Making it seamless between the two is very important.

I still have some concerns about the `128` limit. Another site I'm working on it has as a lot of KB content and the URLs are longer than 128... but I guess I could handle that the same as the e-commerce add on.

**Comment by eric-wilson** [comment]
@i-love-code,

I'm curious about the "generic content model", will it still use `RoutedContentBase` in Core?  If so that will still create a limitation for URL lengths due to:

```
[StringLength(128)]
public string Slug { get; set; }
```

**Comment by i-love-code** [comment]
My apologies @eric-wilson, my comment was meant for #1210 which was referencing commerce implementations in Piranha. I saw this comment come through about nopcommerce/simplcommerce and thought it was the same thread (on mobile).

RE: Slug lengths, I can see how 128 can be too short for a _full_ URL if using a hierarchical and word-based routing and depending on URL structure choice.

That said, if the slug represents only the segment of the URL a single piece of content represents (as it should, in my opinion) then 128 is more than sufficient. This only works if all routing is hierarchical like Piranha's archives are (seen in image below) where the slug is only the URL segment under the blog itself.
![image](https://user-images.githubusercontent.com/1737733/83442962-9be20600-a40e-11ea-85e4-a001c0a53df3.png)

Unfortunately, this isn't the same for nested _pages_, the slug is the entire URL. (seen below) 
![image](https://user-images.githubusercontent.com/1737733/83443073-c633c380-a40e-11ea-894b-54d979bec53b.png)

I'm used to content management systems that allow both, a hierarchical structure-based URL (/about-me/sub-page-with-long-slug in the above example) and a simple/short URL (/long-slug) that's optional.

Just curious, if Piranha's content routing worked similar to archives, where all routing was hierarchical and slug only represented the portion of the URL corresponding to the individual piece of content, would this give you more support in the case of 10,000 products/pages in categories etc?

**Comment by tidyui** [comment]
@i-love-code Well Piranha actually generates hierarchical slugs if the config option `Config. HierarchicalPageSlugs` is set to true (which it is by default). As the slug is generated when the page is saved the first time this only occurs if you actually create the page in the correct position, there's nothing that remaps slugs when you move a page, since this would change the permalink structure and generate dead slugs.

This does however bring up a weakness in the design, that you will run out of space after a certain amount of recursive pages since the slug length is set to `128` on all hierarchical levels.

Now there's two solutions to this.

1. We increase the slug length which solves the problem of this issue and the fact that generated hierarchical slugs can easily exceed the limitation, or
2. Add dynamic routing features where it scans the hierarchical structure to find the suitable page.

Solution 2 would also mean that permalink are automatically updated when a page is moved, which is not optimal unless we would also automatically generate alias rules that would redirect the old permalink to the new whenever a page is moved.

What's your opinion on this @i-love-code @eric-wilson @filipjansson?

**Comment by tidyui** [comment]
Ok, I saw now that there was a new issue opened for this.. I'll move my comment there and close this issue again.
