### ISSUE TITLE
OpenCart integration

### ISSUE THREAD

**Issue by aprokopyev** [PiranhaCMS/piranha.core#1210]
Hello,

It seems OpenCart is the most advanced open source cart and much better than nopCommerce in terms of amount of plugins.

Please suggest what is the best method to integrate it with your CMS?

There are ready integrations with Wordpress and other PHP CMSes:

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=32346
https://wordpress.org/plugins/single-sign-on-sso/

 but I need an ASP.net based CMS for a custom programming, I am only a DotNet coder and prefer VB.net over any other language.

DotNet code for OneAll looks very old:
https://github.com/oneall/dot-net-sdk

Can you please look at it and give me an idea on how difficult it is integrate that old DotNet OneAll code into your Piranha CMS to allow integration with OpenCart?

**Comment by tidyui** [comment]
Since OpenCart is written in PHP integrating it to a .NET Core application would probably be API-based. Whether or not they provide such API:s is nothing I am aware of, you'll have to take a look at their documentation to see what's available for you.

Best regards

**Comment by biapar** [comment]
Simplecart

**Comment by aprokopyev** [comment]
I would prefer my own installation of the shopping cart.
I have discovered recently that OpenCart architecture is ugly:

Most likely I will try Wordpress with Woocommerce, it takes about 30% of the whole amount of sites with their own shopping carts. Not sure how good its architecture is, I am not going to code anything in PHP, so I will use it just as a blackbox though it is open source. Also there is a RESTful API.
Wordpress has a lot of authentication plugins, it will be easy to find a reliable OAuth plugin to connect it to Piranha CMS, where I can do some custom coding if needed.

**Comment by biapar** [comment]
Ok..SimpleCommerce is very simple ecommerce compared to Nop. There are also other ecommerce solution. I don't like WP because is buggy and slower. 
I'm findind a simple method to create a food ordering...without to start from zero doing order model, food model, etc...but I think that if I start from zero I'm more fast that waste time to search.

**Comment by aprokopyev** [comment]
There is an interested project dedicated to run any PHP application like Wordpress (and most likely Woocommerce too) on a DotNet Core runtime:

https://www.peachpie.io/2020/05/how-wordpress-runs-on-dotnet.html

> - We subsequently gain some performance by running and JITtering the application on .NET.
> - We take advantage of fast in-memory response caching.
> - We don’t have our precious source code on the webserver.
> - We can implement widgets, shortcodes, and portions of the web in C#, e.g. using Razor templates.
> - We can implement plugins, e.g. authentication, in C#.
> - We can have a WordPress blog as a part of our C# MVC app.
> - We don’t need PHP installed on the webserver if we prefer the .NET runtime.

**Comment by aprokopyev** [comment]
Does it mean a WordPress site can be embedded into into a Piranha CMS page and vise versa at ASP.net Core Middleware level (NOT just in a HTML frame of course)?

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1

**Comment by tidyui** [comment]
I have no idea, I have never tried peachpie, only read about it brief.

My personal belief is that you should pick the system that suits the application you’re building the best. If you’re building a big e-commerce site I don’t think piranha is the right choice for you atm since we don’t have this functionality or any integrations ready.

The faster way forward would probably be to choose one of the bigger e-commerce options and build the project around that.
