### ISSUE TITLE
Cycle detected when installing Piranha.Data.EF.SQLServer

### ISSUE THREAD

**Issue by DJJones66** [PiranhaCMS/piranha.core#1263]
Cannot use nor install the SQLServer package when using the full source code from git.  

When I used a template and installed it with the -database SQLServer param it worked from there.

**Comment by tidyui** [comment]
Hi there! Could you provide some details on the error:

* Which table is causes the error
* Which foreign key
* Which database & version are you using

The only migration added for `8.4` which is not in `8.3` is this https://github.com/PiranhaCMS/piranha.core/blob/master/data/Piranha.Data.EF.SQLServer/Migrations/20200625060542_AddSiteLogo.cs which doesn't add any references between tables.

Regards

**Comment by DJJones66** [comment]
SQL Server 2019.. and this is happening when installing the package.

**Comment by DJJones66** [comment]
![devenv_owq4fyoCrw](https://user-images.githubusercontent.com/45010408/86415287-8cb3d980-bc94-11ea-8327-9c5016b8d63b.png)

**Comment by tidyui** [comment]
Aha.. I thought you were running on source code and there was a migration error. There is a limitation in `NuGet` which causes cyclic dependencies when trying to install a package into a project with the same name. So the issue here is that you've named your project `Piranha`. When `NuGet` tries to install the package `Piranha` it goes crazy. Try a different name for your project.

As we've had this issue a number of times we'll make sure to add it to the docs, even though one would think `dotnet restore` should handle this more gracefully.

Best regards
