### ISSUE TITLE
WebApp.Url() doesn't work with media assets

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#1312]
The new url helpers `WebApp.Url(...)` and `WebApp.AbsoluteUrl(...)` doesn't work for media assets as the methods append the site prefix if available. This should be solved by adding new methods `WebApp.ContentUrl(...)` and `WebApp.AbsoluteContentUrl(...)` that are suited for uploaded content.

**Comment by StephenWRogers** [comment]
I've a problem with the og:image, which I think is only since upgrading to 8.4.1 which might be because of this change. My images are stored in Azure blob storage and the og:image I'm getting now is

https://<siteurl>https://<image blob url>

which looks like it's coming from this call to AbsoluteContentUrl as AbsoluteUrlStart will be

https://<siteurl>

and ContentUrl will be

https://<image blob url>

which are being appended.

Is this a result of this change, or am I doing something wrong somewhere?

**Comment by tidyui** [comment]
I'll try to reproduce this locally and get back to you!

**Comment by StephenWRogers** [comment]
Did you have any luck with this one?

**Comment by gerardvanderkruijs** [comment]
@tidyui The issue described by @StephenWRogers is still present, also in v9.0.0.
Any chance this issue can be re-opened so it can be fixed?

We're using Amazon S3 storage for our images and the `og:image` tags are rendered as:
`http://localhost:5000https://xxx.s3.eu-west-1.amazonaws.com/xxx.jpg`

**Comment by tidyui** [comment]
@StephenWRogers @gerardvanderkruijs As the initial issue description states `WebApp.Url` and `WebApp.AbsoluteUrl` should not be used for media files anymore. Instead `WebApp.ContentUrl` or `WebApp.AbsoluteContentUrl` should be used. Are you all using the correct methods or using the old methods in your projects?

**Comment by tidyui** [comment]
@gerardvanderkruijs Well the line you're referring to actually **uses** the correct method, i.e `AbsoluteContentUrl`, so if this produces bad output there has to be some kind of bug :)

**Comment by StephenWRogers** [comment]
Yeah I'm the same - I'd just commented on this issue as I think it was the changes from this issue that caused my issue (og:image now using AbsoluteContentUrl which produces the above output), but I guess I should probably have raised it as a new issue.

It looks to me like 

AbsoluteUrlStart will be

https://<-siteurl->

and ContentUrl will be

https://<-image blob url->

which AbsoluteContentUrl appends together
