### ISSUE TITLE
TinyMCE custom init configuration

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#1315]
Hello,

I'm searching everywhere and I can't find anything remotely useful.

As far as I understand, Piranha loads it's own config (`tinymce.init`), where I would need to add the line `fontsize_formats: "8px 10px 12px 13px 14px 16px 18px 24px 36px"`, for example. I found on Gitter (https://gitter.im/PiranhaCMS/Piranha?at=5e78c7a84fa834644901da47), that you can just put the Piranha's file inside the wwwroot folder: `/manager/tiny/piranha.editor.js`. With the original script copied, only the additional line added. This doesn't work for me, editor breaks a bit.

Using `App.Modules.Manager().Scripts.Add("~/js/TinyMCEconfig.js");` in Startup.cs doesn't override anything for me, or I don't understand how to do it.

Ideally I'd want that a user editor can type his own font size, but it's TinyMCE's long-standing problem, as far as I could find.

Thanks

**Comment by tidyui** [comment]
Hi there. Just adding `piranha.editor.js` in your `wwwroot` won't do anything, you need to actually register the js-file that should override the editor with `App.Modules.Manager().Scripts.Add(..)` for it to load.

As custom resources are added **after** the default ones, adding a `.js` that overrides any of the already declared methods will effectively replace it. This said, let's assume you have the following file in your `wwwroot`

~~~
wwwroot/js/customeditor.js
~~~

This file should be registered in your `Startup` with:

~~~ csharp
App.Modules.Manager().Scripts.Add("~/js/customeditor.js");
~~~

And for this file to override how TinyMCE is configured it should override the method `piranha.editor.addInline(..)`. As you can see here the default implementation is empty (https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager/assets/src/js/piranha.editor.js#L9) as this implementation actually gets overridden by the `Piranha.Manager.TinyMCE` module.

This also means that you should add your custom resource in your `Startup` **after** you have called 

~~~ csharp
app.UsePiranha(options =>
{
    ...
    options.UseTinyMCE();
    ...
});
~~~

The reason for adding your script **after** is because you need to override `addInline()` after the TinyMCE module does it.

**Comment by lukasan** [comment]
Thank you for a detailed response.
I copied https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js and added `fontsize_formats: "8px 10px 12px 13px 14px 16px 18px 24px 36px"` at the end of the `tinymce.init` function to the file in  `wwwroot/js/TinyMCEconfig.js`. I still I have the default sizes in pt and no 13 size.

Startup.cs `Configure` function's end:
```C#
            app.UsePiranha(options =>
            {
                options.UseManager();
                options.UseTinyMCE();
                options.UseIdentity();
            });

            App.Modules.Manager().Scripts.Add("~/js/TinyMCEconfig.js");
```

This also doesn't work on a newly created project, so I'm inclined to think that there's a problem with overriding here. The scripts show up in the html, but it doesn't override anything.

![Untitled](https://user-images.githubusercontent.com/60816397/91292706-9131d580-e79f-11ea-83c1-c85e8e7c77d7.png)

**Comment by tidyui** [comment]
Hi again. I have investigated some more, and due to how resources are loaded it's not possible to override `piranha.editor.js` the way I described as it is a "page specific" resource, and not a global resource. Instead we can rely on the fact that the middleware for `static files` are executed **before** `embedded files`. This means that you can copy `piranha.editor.js` from the `Piranha.Manager.TinyMCE` project and put it in your local project in:

~~~
~/wwwroot/manager/tiny/piranha.editor.js
~~~

This way when the resource is requested by the TinyMCE module your local version is returned instead of the embedded version. Hope this makes sense!

**Comment by axunonb** [comment]
[This](https://github.com/PiranhaCMS/piranha.core/issues/1315#issuecomment-680826891) works perfectly. Thank you. I came across the same requirement as @lukasan.
I was thinking about giving "power users" (role based) more features, and use the default settings for others. I did the following:

1. Control the settings in [_EditorConfig.cshtml](core/Piranha.Manager/Areas/Manager/Shared/Partial/_EditorConfig.cshtml):
```html
@using Piranha.Manager.Editor
<script>
    piranha.editorconfig = new function() {
        "use strict";
        // other settings
        this.menubar = @User.HasClaim(c => c.Value.Equals("poweruser"));  // New: show the menu bar if required
    };
</script>
```
2. Copy [piranha.editor.js](core/Piranha.Manager.TinyMCE/assets/piranha.editor.js) to ```~/wwwroot/manager/tiny/piranha.editor.js```

3. Modify ```~/wwwroot/manager/tiny/piranha.editor.js``` to use the setting from ```piranha.editorconfig```:
```js
piranha.editor.addInline = function (id, toolbarId) {
    tinymce.init({
        selector: "#" + id,
        browser_spellcheck: true,
        fixed_toolbar_container: "#" + toolbarId,
        menubar: piranha.editorconfig.menubar,  // New setting
        // other settings
    });
}
```
@tidyui: Would a PR be acceptable, bringing more configuration options form [_EditorConfig.cshtml](core/Piranha.Manager/Areas/Manager/Shared/Partial/_EditorConfig.cshtml) to piranha.editor.js (like described above, but with piranha.editor.js taking over settings out-of-the-box)?

**Comment by tidyui** [comment]
@axunonb Cool solution! However bringing in such a solution into the core is hard, because if we allow configuring the toolbar  using the claims of the current user, then lot's of other features should be able to configure this way as well. A good middle way would be to stick with the current `.json` configuration and maybe extend it with some more common properties. For more complex solutions maybe the entire object used for initialization could be overridden by an object that can be created from a `.cshtml` file, for example:

*MyCustomSetup.cshtml*
~~~ csharp
<script>
    piranha.editor.config = {
        selector: "#" + id,
        // Setup editor any way desired
    };
</script>
~~~

As it would set a member in the `piranha.editor` object, `piranha.editor.addInline()` could check if this object is set, and if so just use the manual configuration instead.

**Comment by axunonb** [comment]
> bringing in such a solution into the core is hard, because if we allow configuring the menubar using the claims of the current user

Yeah, absolutely, this would be too special for the core. Looks like I was not clear enough.

> set a member in the `piranha.editor` object, `piranha.editor.addInline()` could check if this object is set, and if so just use the manual configuration instead.

It's just about taking over most of the hard-coded settings in ```piranha.editor.js``` by configurable ones like you pointed out.
That's what I meant for a PR.

**Comment by lukasan** [comment]
Hey, @tidyui, I'm not sure why my first override from Gitter didn't work.
Copying https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Manager.TinyMCE/assets/piranha.editor.js and changing the init function to my needs, placing it into folder:
```
~/wwwroot/manager/tiny/piranha.editor.js
```
Everything works, thanks!
