### ISSUE TITLE
error with Module with Own Context: Table 'piranha_aliases' already exists

### ISSUE THREAD

**Issue by mrccarvalho** [PiranhaCMS/piranha.core#1388]
Hi!
I created my own Database Context named "MyContext" inherited from DbContext.
I´ve got this error
Table 'piranha_aliases' already exists.

The piranha tables are created successfully, and i can apply migrations of MyContext and i can update the database successfully too.
But when i do "dotnet run" the error appears...Table 'piranha_aliases' already exists.

MyContext class:

`
public sealed class MyContext : DbContext
{
        public DbSet<Person> Persons{ get; set; }
        public MyContext(DbContextOptions<MyContext> options) : base(options)
        {   
            Database.Migrate();
        }
 } 
`
Thanks

**Comment by tidyui** [comment]
What version of Piranha are you using and what database?

**Comment by mrccarvalho** [comment]
piranha: "8.3.0"
mysql: 5.6.17

thanks again

**Comment by tidyui** [comment]
Are you referencing any of the data entities in the Piranha `DbContext` from your context, because if so it could try to create them again?

**Comment by mrccarvalho** [comment]
It works after upgrade mysql server to 5.7.32.
And yes, i'm referencing entities...should not do this ?

thanks for your help.

**Comment by tidyui** [comment]
If you're referencing entities from another `DbContext` your context will try to create them in it's migration as well. This will lead to duplicate create statements and errors while running the migrations. Instead you have to rely on software triggers (hooks) to keep database integrity for foreign keys.

**Comment by tidyui** [comment]
However, since Piranha is explicitly naming tables to `Piranha_TableName` in the `OnModelCreating` method, most likely you would get duplicate tables in your database. Problem here is it will be really hard for you to tell where the data is ending up, so my answer is **no**. You should never reference entities that belong to another context **unless** you add `Ignore()` to the properties in `OnModelCreating` (this can be useful if you want to fill them with data from the other context in a service for example).

**Comment by mrccarvalho** [comment]
Understood! Thank you for the explanation.
