### ISSUE TITLE
manager login redirecting to account endpoint

### ISSUE THREAD

**Issue by general-adhoc** [PiranhaCMS/piranha.core#1416]
Completing a migration from 6.X to 8.X, and we keep running into an issue where 

http://localhost:1234/Manager 

is redirecting to 

http://localhost:1234/Account/Login?ReturnUrl=%2Fmanager

which is not a real page.  We're running a headless CMS, where the correct login page is actually:

http://localhost:1234/Manager/Login

Do you know how we can reconfigure the routing to not try to send to an /Account page or endpoint that doesn't exist?

The only routing code we have setup is:

```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");

                endpoints.MapPiranhaManager();
            });
```

Thanks to the PiranhaCMS team for all the support and an overall great library

**Comment by tidyui** [comment]
Try to use the new startup methods instead of the old ones to see if it works. For a headless application, disable all routing features in `ConfigureServices()` by adding:

~~~ csharp
services.AddPiranha(options =>
{
    ...

    options.UseAliasRouting = false;
    options.UseArchiveRouting = false;
    options.UsePageRouting = false;
    options.UsePostRouting = false;
    options.UseSitemapRouting = false;
    options.UseSiteRouting = false;
    options.UseSiteRouting = false;

    ...
});
~~~

In the upcoming `9.0` version there is a new convenience method for this.

~~~ csharp
services.AddPiranha(options =>
{
    ...

    options.DisableRouting();

    ...
});
~~~
