### ISSUE TITLE
Detect EXIF orientation on mobile pictures

### ISSUE THREAD

**Issue by gpcottle** [PiranhaCMS/piranha.core#1442]
Hello,
I have tried creating a blog entry and selected a portrait image to go with it. It seems that when I do so, the Image Processing crops it based on the longest edge and the new files created are not in the right direction.
For example, I added a file with dimensions 2448x3264 (taken on a mobile). Three additional files were created

- IMG_210x160 - has size 160x210
- IMG_1140x450 - has size 450x1140
- IMG_1920x400 - has size 400x1920
I know the final image is used as a banner on the post and I can see the app then crops again to get the banner and thus is scaling a second time. 
Is it intentional to create the files this way? Not a big deal as I can watch out for it and only use landscape images which do get processed to create the files in the right direction.
Thanks
Graham

**Comment by tidyui** [comment]
That doesn’t sound right. Before I dig into this, are you 100% the image is in portrait, because often phones actually take landscape photos but add a rotation flag in the file header.

**Comment by gpcottle** [comment]
Hello,
I am reasonably certain that the photo is portrait. I checked the attributes as I see them in Explorer and cannot see anything which would indicate a rotation flag. I have attached the photo in case you can see anything different.
![IMG_0068](https://user-images.githubusercontent.com/19620782/103149995-24d3dc80-4767-11eb-897c-f6f68609227b.JPG)
Thanks
Graham

**Comment by tidyui** [comment]
Thanks for the image, I'll test and try to reproduce the issue! Cute dog, I've got a Golden Retriever myself :)

**Comment by tidyui** [comment]
I uploaded your file, and like you say it gives the following information in the manager when looking at the details (i.e landscape orientation).

<img width="785" alt="Skärmavbild 2021-01-01 kl  13 27 15" src="https://user-images.githubusercontent.com/781266/103438653-37518880-4c35-11eb-96e2-95ed16f3bee8.png">

Looking at the file info in Finder I can see that the image origin is an `iPhone 5s`. I know for a fact that these phones **always** take photos in landscape mode and then add orientation in the EXIF meta data regarding how the phone was positioned when taking the photograph. I opened the image in Photoshop and then exported it with "Save for web" which removes this meta-data and saves the image as is, then it shows the following details in the manager.

[5009924.pdf](https://github.com/PiranhaCMS/piranha.core/files/5758911/5009924.pdf)

So the real issue here is, can we (and should we) automatically detect these things when an image is uploaded and then perform an automatic image rotation before storing it in the media library.

**Comment by tidyui** [comment]
Sorry for the interface being in Swedish, that's my default setting and I always forget to change it before taking screenshots :)

**Comment by gpcottle** [comment]
Hi - many thanks for taking a look. I didn't see any kind of rotation flag within the file, but I will be vigilant for future uses of such images and appreciate your considering it for an enhancement. The image of the dog was purely for my playing purposes and not intended to be a site for dog pictures.
I am liking the architecture of the CMS a lot and have managed to customise bits here and there for my own site, which is still very much in development. 
Best wishes
Graham
