### ISSUE TITLE
Piranha can be used as headless backend data container ?

### ISSUE THREAD

**Issue by biapar** [PiranhaCMS/piranha.core#1488]
Piranha can be used as headless backend data container ?

**Comment by tidyui** [comment]
Yes. Everything in Piranha is based on the `IApi` service that is injected everywhere. We have a **basic** package you can include to add API-endpoints which is called `Piranha.WebApi` (https://www.nuget.org/packages/Piranha.WebApi) but we strongly encourage everyone to just create their own Api Controllers that operate on the `IApi` and exposes the endpoints that they need for their particular application.

We also have a project template that just sets up an empty web application with the manager interface that is perfect for creating a backend for a headless application.

~~~
dotnet new piranha.empty
~~~

Regards

**Comment by biapar** [comment]
Thanks. I'm exploring possibility applications ( I preferr on .NET ) like strapi.io / Orchard  and so to use ad BE for a new Xamarin Forms App

**Comment by ChrisProlls** [comment]
Hi @tidyui, I have the feeling that PiranhaCMS is all about managing pages / posts / blog / sites, but what if I want to manage a larger panels of content data through collection types ? (like in Strapi)
For exemple, a list of restaurants ? Is that possible ?

**Comment by r4g-jon** [comment]
Hi @ChrisProlls 

I've used Piranha on a few sites and whilst it can manage pages etc like you say, it can also do more than that. We've used it to manage content and our users have been really happy with it as it's very easy to use. 

I don't know how many restaurants you are looking at, so I can't give you a definite "yes it will handle it", but we've used Piranha to manage a list of partners and it's been fine. There's around 100 of them and we have had no problem with it at all. Loading the pages is quick on the website. It might be a little tricky using the CMS if you have, for example, thousands of restaurants however. 

If your restaurants are currently in another CMS, you can quite easily import the data into Piranha too.

**Comment by biapar** [comment]
> Hi @ChrisProlls
> 
> I've used Piranha on a few sites and whilst it can manage pages etc like you say, it can also do more than that. We've used it to manage content and our users have been really happy with it as it's very easy to use.
> 
> I don't know how many restaurants you are looking at, so I can't give you a definite "yes it will handle it", but we've used Piranha to manage a list of partners and it's been fine. There's around 100 of them and we have had no problem with it at all. Loading the pages is quick on the website. It might be a little tricky using the CMS if you have, for example, thousands of restaurants however.
> 
> If your restaurants are currently in another CMS, you can quite easily import the data into Piranha too.

Is there an example? I'm interesting too.

**Comment by biapar** [comment]
> Hi @tidyui, I have the feeling that PiranhaCMS is all about managing pages / posts / blog / sites, but what if I want to manage a larger panels of content data through collection types ? (like in Strapi)
> For exemple, a list of restaurants ? Is that possible ?

Check Directus.io, too.

**Comment by tidyui** [comment]
I'll try to answer from a technical point of view @ChrisProlls 

You can create any kind of data that you want, with the structure and fields you like. Depending on how you build your application you could add restaurants as either:

* Pages (just in the site-structure)
* Posts (In an "Restaurants" archive which gives you access to categorization and tagging)
* Generic content (If you should navigate directly to the content but it should be used in another page or posts's context)

Given the amount of data you can add there's really no limit except how the system works. Since the relational data is structured in different way than your application models, it will need to be transformed when you load it. As data transformation (and database access) always takes the most time in any application there is of course caching available, where at the highest level all readily transformed application models are held in cache, and purged when updated.

You will always need to take into account just how many objects you will store in the cache, for a small to medium sized web application there's absolutely no problem with keeping everything in cache, but if you plan on storing tens of thousands of entities this will of course increase memory consumption.

The other aspect to keep in mind is usability of the admin/management UI. Piranha has been optimized for small to medium sized application and might not provide the tools you'd like when working with really large sets of data. This doesn't mean that we can't incorporate such features if it is beneficial for the library, but it's still something to keep in mind.

Best regards

Håkan

**Comment by tidyui** [comment]
And as always. Please open a **new** issue if you want to report something, or use the "Discussion" feature available in the repository instead of commenting on old closed issues.

Best regards

**Comment by ChrisProlls** [comment]
Wow! So much answers :)
I was exploring the possibility of such a feature with PiranhaCMS like I can do today with Strapi.io called `Content Builder`, where I can just build a structure (like restaurant with 2 fields : title and description) and add content to my CMS following this structure and make it accessible through REST API.

I understand the performance/usability with PiranhaCMS, thanks for pointing me out this.

Thanks for your answers! :)

**Comment by biapar** [comment]
Headless is "a must" and a good think to exchange data. @tidyui Is there an example to use Piranha as dataset manager and rest api / graph api?

**Comment by biapar** [comment]
@ChrisProlls I don't found anything in .NET like Strapi/Directus with headless function out of the box.

**Comment by ChrisProlls** [comment]
No problem @biapar, thanks for your update ! :)

**Comment by biapar** [comment]
@ChrisProlls Have you some example ?

**Comment by tidyui** [comment]
Please don’t add new comments into old closed issues. Instead create a new issue or open a discussion for it.

Best regards
