### ISSUE TITLE
the new user does't login 

### ISSUE THREAD

**Issue by ademsenel** [PiranhaCMS/piranha.core#1496]
login page doesn't redirect into manager page after crate a new user  Version 8.4.1

**Comment by tidyui** [comment]
As this is not a previously reported issue and this version has been available for six months it most likely has something to do with the project setup. Have you installed the correct `Piranha.AspNetCore.Identity` packages to match you database, otherwise roles and claims might not work properly as migrations differ.

Also have you made sure that cookies from the web application are not discarded by the browser.

Best regards

**Comment by ademsenel** [comment]
İ tried all also download core from github but the issue is same

**Comment by jensbrak** [comment]
@ademsenel - Are you using own code or a Piranha template? Did it work with a previous version of Piranha? I had issues with manager redirect but resorted those, but not knowing more of your setup makes it hard to come with suggestions.

**Comment by ademsenel** [comment]
hi dear 
i used both template and core i didnt work before first time usued
i tried and want to use it

**Comment by ademsenel** [comment]
i am sorry i found what is wrong 
when i created role i didnt check Admin check box
when i marked Admin check box everything woked as expected

one more question i would like to change manager user interface language doesn it possible

**Comment by tidyui** [comment]
The language is chosen according to the culture of the computer/server running the application. You can check the currently available languages here:

https://crowdin.com/project/piranhacms

Regards
