### ISSUE TITLE
Generic content question(s)

### ISSUE THREAD

**Issue by SoftWebMike** [PiranhaCMS/piranha.core#1510]
Hope you are well!

I had 2 questions that relate to the new generic content, and was wondering what your thoughts/plans are:

Is there a way, current of future, to use generic content to fuel blocks or page elements. Take products for example, you can currently add products to a page using the ContentInfo type and select products through the manager. I can get this information within the model via the region, however these are only references. I guess the questions are:

1. Is/will there be support for getting the full model for generic content - I could use the IContentService (I think), however I would have to get one at a time. Is there plans to introduce a get(ids[])?
2. Is/will there be support for allowing content driven templates? So a user could build up a page template where content specific parts are used within target sections

(2) example could be:
<header> {{product.Name}}</header>
<description> {{ product.Description }}

The content editor can then add a section of say <image /> between the header and description parts, and it would update all the "product driven" pages to include that. I realise that this could be done programmatically, however it would be a great win if the content users were able to use the manager to build these pages.

Another question, is there any way presently/future to have a hook into the content save process to allow additional pre/post save processes to take place? 

Thoughts welcome

**Comment by SoftWebMike** [comment]
Further to the last questions, is/will there be the ability to use the manager to update content from else where in the code base. 
For example, could I store products within a micro service, and then translate it to a localised GenericContent model which would allow me to essentially use the manager to manage the content from outside of the GenericContent framework?

**Comment by tidyui** [comment]
Hi there! Good questions, I'll do my best to answer them :)

1. The full content model will not be loaded automatically, this is not done for pages or posts either. The reason for this is simply a safety mechanism to avoid endless recursion as it's fully possible to add a reference to something that then has a reference back to the page/post. We will be adding methods for getting data for multiple id's (#1364), this has already been added to some of the services.
2. As Piranha is a fully decoupled CMS we don't normally include components for adding information about how the content should be rendered. It would however be fully possible for you to add this functionality yourself by creating your own custom fields/blocks for this that would allow the editor to enter this kind of information.
3. Thanks for noticing this. Hooks should be included for `9.0`, this must've been missed during development.
4. We have not discussed this feature, instead we try to add as many UI-tools as possible to the manager so that it will be efficient for developers to add their own custom pages to the manager.

**Comment by tidyui** [comment]
Added an issue for the missing hooks (#1511).

**Comment by SoftWebMike** [comment]
Hi Håkan,

Thank you for the reply and your continued support.
I look forward to the 9.0 release :-)

Mike
