### ISSUE TITLE
Azure MvcWeb: HTTP Error 500.30 - ASP.NET Core app failed to start (The InternalId field must be unique)

### ISSUE THREAD

**Issue by Neteklab** [PiranhaCMS/piranha.core#1545]
System.ComponentModel.DataAnnotations.ValidationException: The InternalId field must be unique

   at Piranha.Services.SiteService.SaveAsync(Site model) in \piranha.core-9.0\core\Piranha\Services\SiteService.cs:line 317

   at MvcWeb.Seed.RunAsync(IApi api) in \piranha.core-9.0\examples\MvcWeb\Seed.cs:line 40

**Comment by tidyui** [comment]
I've just tried the following:

~~~
dotnet new --install Piranha.Templates::9.0.0
dotnet new piranha.mvc
~~~

Project is created, compiled and seeded without issues. The error you're providing is usually because of some other underlying issue.

1. Where are you running the application, local or on a production environment?
2. What database are you using?
3. Are you using the correct `Piranha.Data` and `Piranha.AspNetCore.Identity` packages for your database?

Regards

**Comment by Neteklab** [comment]
Thanks for reply

1. Version 9.0.0 release, deployed on Azure
2. SQlite
3. Bundled

Fixed it by removing automatically deployed piranha.mvcweb.db file and additionally setting all files in the seed directory to "copy to output directory".

Issue can be closed.
