### ISSUE TITLE
Issue updating from version 8.4.2 -> 9.0.1 Piranha.Models.RegionType missing error

### ISSUE THREAD

**Issue by hedronn** [PiranhaCMS/piranha.core#1593]
I have attempted to update to version 9.0.1 from version 8.4.2 and and encountered the following error  - JsonSerializationException: Could not find type 'Piranha.Models.RegionType' in assembly 'Piranha, Version=9.0.1.0, Culture=neutral, PublicKeyToken=null'

Newtonsoft.Json.JsonSerializationException: 'Error resolving type specified in JSON 'System.Collections.Generic.List`1[[Piranha.Models.RegionType, Piranha]], System.Private.CoreLib'. Path '$values[0].Regions.$type', line 1, position 676.'

Is this a .NET 5 serializing issue with NewtonSoft vs System.Text.Json serializer perhaps?...has anyone else experienced this issue upgrading from 8x to 9x?

**Comment by hedronn** [comment]
Moved to discussion board - https://github.com/PiranhaCMS/piranha.core/discussions/1595

**Comment by hedronn** [comment]
Re-opened - After investigating this a little more, i do not see any old reference problems with the upgrade from 8x to 9x or with the database that i can detect post upgrade attempt.

Can someone help point me in the right direction so i can resolve this upgrade issue?

**Comment by tidyui** [comment]
Trying to figure out where the error could come from. The only default data that is serialized directly with `Json.NET` is:

1. Content Types
2. Page & Post revisions

As the missing type `RegionType`, which has been renamed to `ContentTypeRegion` is only used in Content Types the logical guess would be that there's an error when trying to deserialize one of the content types. The weird thing though is that  when I look the body is serialized in an `8.4.1` application the type definition from the error message is not used, i.e:

~~~
System.Collections.Generic.List`1[[Piranha.Models.RegionType, Piranha]]
~~~

`Json.NET` only prints out type information like this when serializing an object where a property has a non finite type, for example if you serialize the following object:

~~~ csharp
public class MyObject
{
    public IList<IMyInterface> Items { get; set; }
}
~~~

Then the serialization will include full type information so that it can be determined what objects should be instantiated when populating the `Items` collection. Are you serializing any data in your application that could cause the error?

**Comment by tidyui** [comment]
Are you running some kind of persistent cache that uses `JSON` serialization that hasn't been cleared?

**Comment by hedronn** [comment]
I will investigate further and check for cached objects. The project is using an Azure redis distributed caching service.

**Comment by hedronn** [comment]
Ok cleared cache and that has resolved that specific error first encountered. Oddly now i am seeing a NULL **Sitemap** in @WebApp.Site.**Sitemap** object when using the SiteHelper, has this been changed?

**Comment by hedronn** [comment]
Ah it appears in v9x app.UsePiranhaSitemap(); i am using in the Startup is NO longer available.

**Comment by hedronn** [comment]
ok i have seen services.AddPiranhaApplication(); in the Piranha.org docs, however i have the package installed Piranha.AspNetCore v9.0.1 but i cannot use services.AddPiranhaApplication(); in my startup as its NOT recognised - IServiceCollection does NOT contain a definition for AddPiranhaApplication. I checked and i have the following Piranha packages.

    <PackageReference Include="Piranha" Version="9.0.1" />
    <PackageReference Include="Piranha.AspNetCore" Version="9.0.1" />
    <PackageReference Include="Piranha.AttributeBuilder" Version="9.0.1" />
    <PackageReference Include="Piranha.Azure.BlobStorage" Version="9.0.0" />
    <PackageReference Include="Piranha.Data.EF.SQLServer" Version="9.0.0" />
    <PackageReference Include="Piranha.ImageSharp" Version="9.0.0" />
    <PackageReference Include="Piranha.Manager.TinyMCE" Version="9.0.0" />
    <PackageReference Include="Piranha.WebApi" Version="9.0.0" />

**Comment by tidyui** [comment]
All of the old startup methods from previous version have been removed. Startup should be build according to the current pattern, see: 

* https://piranhacms.org/docs/master/basics/application-setup
* https://piranhacms.org/docs/master/basics/startup-options

You can also create a new application from one of the current templates to have the code generated for you.

Best regards
