### ISSUE TITLE
No Posts in WebApp.Site.Sitemap

### ISSUE THREAD

**Issue by tophermurphy** [PiranhaCMS/piranha.core#1632]
The main nav shows archive pages as having no children and posts and post types have no option for "isHidden"

**Comment by tidyui** [comment]
Posts are not positioned in the hierarchical navigation, they belong to an archive page in the structure.

**Comment by tophermurphy** [comment]
I really wish this was an option. It is a little too opinionated on the content model.

**Comment by tidyui** [comment]
Well this particular design decision has been the same since the first version of Piranha back in 2011/2012 and it’s highly unlikely it will ever change. If you want to position items in the site map you should use pages, but there’s nothing preventing you from adding articles/posts as a page model.

Regards
