### ISSUE TITLE
Cannot edit a user in version 9.1.1

### ISSUE THREAD

**Issue by wilmarmacosta** [PiranhaCMS/piranha.core#1709]
In version 9.1.1, the edit user page returns a blank page.

**Comment by tidyui** [comment]
Can’t reproduce with the latest template and packages. How is your application set up?

**Comment by tidyui** [comment]
Possibly duplicate of #1678

**Comment by tidyui** [comment]
Could you please confirm if this is a duplicate?

**Comment by RickIsWright** [comment]
Issue: When editing a user in 9.1.1, the full URL is not built, so the url becomes https://manager/user/8644c909-b6fc-4e6e-ad44-63cf044beacd instead of https://someurl.com/manager/[GUID].  If you manually edit the url and prepend the base url of somesite.com/ before the manager segment, you can edit the user. Can you confirm?

**Comment by wilmarmacosta** [comment]
Sorry for the late reply, i reverted to version 9.1.0 because of this
issue. I can confirm that the base url is present during the test and it
returns a blank page.

All works fine except this issue that I am unable to edit a user.

Regards,
Wilmar

**Comment by ramimod** [comment]
Change line 

<a :href="'@Url.Content("~/")/manager/user/' + user.id">{{ user.userName }}</a>

**with**

<a :href="'@Url.Content("~/manager/user/")' + user.id">{{ user.userName }}</a>

identity\Piranha.AspNetCore.Identity\Areas\Manager\Views\User\List.cshtml
