### ISSUE TITLE
 You cannot add a new user if you do not have Edit Users permission.

### ISSUE THREAD

**Issue by HusseinKhodadadi** [PiranhaCMS/piranha.core#1774]
When user does not have Edit Users permission, clicking on add button for adding new user, will redirect to login page.

**Comment by tidyui** [comment]
Actually, all of the permissions are designed so that you need `Edit` to actually open an item in the `EditView`. `Add` is an extra permission that specifies if you can create new items or only view/modify existing ones. It doesn't make much sense to let a user create new items, but deny them to update them, in case the mistyped something.

Regards
