### ISSUE TITLE
Extensible modules, Dashboard in Piranha

### ISSUE THREAD

**Issue by papyr** [PiranhaCMS/piranha.core#1802]
Hello, this is the right mix and balance, between orchard, ABP (too pricey) or umbraco. I like how its implemented.. I want to see if it can replace another transactional CMS, use case is small ware house which lists recycling metals etc.

For the developer who want to extend or build modules

- [ ] Can you please add a `diagram / architecture / components / hooks`
- [ ] Have a list of modules on your web site (add modules like WP from admin site)
- [ ] One key feature clients are looking for are a [Dashboard](https://github.com/jdanylko/Tuxboard)/widgets (stock items, people working, outstanding tickets)
- [ ] Auto Update /notification from inside Piranha , login in audits low priority
- [ ] [Scaffolder Module or Model](https://github.com/EasyAbp/AbpHelper.GUI) /[e.g. Generator Settings](https://github.com/EasyAbp/Abp.SettingUi) for boiler plate module, so we can build quickly
- [ ] How to theme the UI, custom themes
- [ ] ElasticSearch / Lucene
- [ ] User Roles/Claims Management
- [ ] Are you planning enterprise version when its stable, will it be affordable for SMB

A very nice read on [widgets](https://support.monday.com/hc/en-us/articles/360007078739-The-Overview-Widget), now with tailwind it should be much more easier for developers, since they add them as components.

![image](https://user-images.githubusercontent.com/12733414/148136648-d9a9dfa4-2730-480f-8fb5-49e1fabc9418.png)

![image](https://user-images.githubusercontent.com/12733414/148136701-6dc0cfd8-831d-4f14-a1e6-6e00ef4cc39e.png)

**Comment by tidyui** [comment]
Piranha is a decoupled CMS and simply doesn’t have an architecture that supports some of your requirements.

1. Hooks: https://piranhacms.org/docs/master/application/hooks
2. Modules can’t be added from the UI. Modules are usually NuGet packages that needs to be added to the project by a developer.
3. Our admin doesn’t have a dashboard. We’ve discussed it on numerous occasions but it hasn’t been prioritized. However since the admin is totally extendible you can add your own dashboard.
4. Update requires updating NuGet packages with binary dll’s, ie must be done by a developer 
5. We have some .NET project templates 
6. Piranha is decoupled, there are no themes. However you can change the web application any way you like
7. We’ve started working on a search implementation for Azure Search, but it is not production ready.
8. Exists in the Identity module.
9. We are not planning an Paid Enterprise version. Piranha is a free open source framework.

best regards
