### ISSUE TITLE
.UsePiranha(options) middleware ruins searching in routes (LinkGenerator API)

### ISSUE THREAD

**Issue by Hockwell** [PiranhaCMS/piranha.core#1816]
- **Issue**: Html.Action, Html.BeginForm,...,Url.Action() generate a default route to action (ControllerName/ActionName?params), but not a special route from .MapControllerRoute()-methods (attribute-based routes work fine). Issue was discovered after migration from 3.1 to .net 6 and piranha 10.

Example (I have a lot more examples): for this rule LinkGenerator API generates Purchase/Buy
```
endpoints.MapControllerRoute(
         name: "Buy",
         pattern: "api/purchase/buy/",
         defaults: new { controller = "Purchase", action = "Buy" }
         );
```

- **Mitigation:** using old piranha middleware, for example: .UsePiranhaManager(), .UsePiranhaTinyMCE(), .UsePiranhaIdentity() instead of UsePiranha().

**Comment by tidyui** [comment]
The problem here was that there is a problem with calling `UseEndpoints()` multiple times. To amend this we have added a `UseEndpoints()` method to the `PiranhaApplicationBuilder` that will add the endpoint actions to a collection and then call them all in one go. This method can be called from within `UsePiranha()`, for example:

~~~
public void Configure(...)
{
   ...

   app.UsePiranha(options =>
   {
      options.UseEndpoints(endpoints => ...);
   });
}
~~~
