### ISSUE TITLE
Access Site

### ISSUE THREAD

**Issue by AbdullahEliwa** [PiranhaCMS/piranha.core#1869]
Hi, just downloading piranhaCms and playing with it
So now I created new site, So now I have two sites, the default one and other one called **Test**
Now how exactly can I access test and it's inner page ?
the only way I can do it is by making it default site and now I can't access the Default site
What I want it to can access both sites (or more) dynamically without any need to write code, so I can add many site as I want with it's pages/content. 
*** Note: I'm doing this locally.

**Comment by tidyui** [comment]
You have two options:

1. Enter a desired hostname in the site information for your second site and add the same hostname in your local host config so that requests are routed to your local machine.
2. Enter a suffix hostname for your second site in the site information, for example “localhost/secondsite”

Regards

**Comment by AbdullahEliwa** [comment]
Thanks, that works well, now I can access the second site main/home page, but when trying to navigate to any other pages inside it 404 is the result.

**Comment by AbdullahEliwa** [comment]
Just figure out the route is case sensitive !!
working well with event not with Event
Anyway thank, But other question, Can I Customize the layout (footer, navbar) for each individual site ?

**Comment by tidyui** [comment]
When the request hits the controller it’s all just standard MVC, so you should be able to handle this in your views.
