### ISSUE TITLE
Fetching custom regions via the api

### ISSUE THREAD

**Issue by liamkavfc** [PiranhaCMS/piranha.core#1961]
I want to use Piranha in headless mode so have been playing with the api to see its capabilities, but when I added a custom region to my custom page type, the api threw an Exception as it didnt know how to handle my custom region. Is this just not available to do? Or is the something more I have to do?

```
[PageType]
public class MyPage : Page<MyPage>
{
   [Region]
    public MyBody HtmlBody { get; set; }
}

public class MyBody
{
    [Field]
    public HtmlField Body { get; set; }
}
```

**Comment by tidyui** [comment]
Hi there! The problem here is that the serialization/deserialization does not support class regions with a single property (see https://piranhacms.org/docs/master/content/regions for reference). If your region will only contain a single field, the correct way is to add that field directly as the region:

~~~ csharp
public class MyPage : Page<MyPage>
{
   [Region]
   public HtmlField HtmlBody { get; set; }
}
~~~

Best regards
