### ISSUE TITLE
Manager redirects uses incorrect url when running in Azure

### ISSUE THREAD

**Issue by EddyCwdry** [PiranhaCMS/piranha.core#2013]
**Description:**
When deploying a Piranha CMS website on Azure and accessing the admin manager interface, a domain redirection issue occurs. Currently, when attempting to access the manager interface at `xyz.com/manager`, the redirection leads to `xyz-cms.azurewebsites.net/manager` instead of using the original domain.

**Expected Behavior:**
The expected behavior is for the Piranha CMS manager interface to utilize the domain that was originally requested (xyz.com in this case) or provide an option for configurable domain settings.

**Steps to Reproduce:**

1. Deploy a Piranha CMS website on Azure
2. Configure a custom domain
3. Access the manager interface using the URL `xyz.com/manager`.

**Actual Result:**
The URL is redirected to xyz-cms.azurewebsites.net/manager instead of using the original domain.

**Desired Result:**
The manager interface should maintain the original domain (xyz.com) or offer a configuration option to specify the desired domain.

**Additional Notes:**
This issue is a problem as it is preferable to not expose the .azurewebsites domain, and it is impossible to lock them down without piranha's manager from being unreachable. I have only tested this with AFD in place so that may be a complication, but I believe this behavior would happen for any cloud hosting environment

**Comment by tidyui** [comment]
Hi there! Are you running your website on Linux in Azure and what version of Piranha are you using? Since the manager only performs standard `ASP.NET` redirects, it redirects to the hostname that is known to the server running the application. If redirects are done on the internal URL the reason has to be that the host headers haven't been forwarded properly to the server from the proxy.

We've seen similar problems in the past on nginx where the schema wasn't forwarded and the manager redirected from `https` to `http` as it was unaware of the schema being used in the request to the proxy.

Best regards

**Comment by EddyCwdry** [comment]
Currently our CMSs are currently on `10.2.0` and they are running on windows instances on azure. From what you're saying it sounds like it could be an issue with our AFD configuration so I will investigate that and update the issue .

**Comment by EddyCwdry** [comment]
Thanks for the assistance, I got our Azure team to take a closer look at their forwarding rules and this was able to resolve the issue.
