### ISSUE TITLE
Add version param to PublicUrl in FileStorage

### ISSUE THREAD

**Issue by lukasan** [PiranhaCMS/piranha.core#2061]
Hello,
I came across an issue with file updating.
I have a website that saves and serves files like doc, pdf, docx and etc. into local storage.
Using `Piranha 10.3.0`.

Steps to reproduce:

1. Open `details` of any editable file in `Media`, like a `.docx`, maybe even a `.txt` would work.
2. Download the file using `URL` (not `Download`)
3. Change the content of the file
4. In `Update` tab of the file, upload the changed file.
5. Details tab of the file click `Download media` link - downloaded file is actually changed, works as expected.
6. Click on `URL` - returns the previously cached downloaded version.

I have custom blocks with `Tiny` editor that link to the file. I don't know if there is a way to serve such files, only with a link to the file in the blocks.

It does not matter if I add or remove inside of `AddPiranha`:
```C#
options.UseMemoryCache();
```
that is `PiranhaServiceBuilder`.

Changing cache level also does not do anything here:
```C#
Piranha.App.CacheLevel = Piranha.Cache.CacheLevel.None;
```

the result is the same. Is it even a `Piranha` issue?
I noticed https://github.com/PiranhaCMS/piranha.core/issues/502 but the requirement is that the link should stay the same. So no version appends or anything.

Tested on Edge and Firefox.

**Comment by tidyui** [comment]
Hi there! The public URL used to retrieved an asset is not proxied through any code from Piranha, the storage providers we provide `Local.FileStorage` and `Azure.BlobStorage` exposes the public URL for the asset which is then handled either by Asp.net or by Azure. In either case these providers usually provide cache headers to make sure browsers cache assets and this is probably the root cause, not anything done by Piranha.

The cache code you're referring to handles server-side caching of the model class which (like you noticed) won't affect the browser cache for images.

The easiest way to deal with this problem would probably be to append a query string parameter to the URL of your asset, like `?version=xxx` where the version number could be a  hash generated from the `LastModified` date of the asset. This way browsers will use the cached image as long as your version-id remains the same, but after the file has been updated the id is updated and the browser should re-fetch the image.

Please note that if you're using a CDN that caches all assets this has to be configured properly as well.

Regards

**Comment by lukasan** [comment]
Thank you for a detailed response!

Unfortunately, I cannot change the path in any way or I would need to change the content in blocks for each appearance.

Can't I extend `Local.FileStorage` to add no cache headers? I searched for a solution, but couldn't find anything that works. And disabling cache overall is probably a bad idea. And any middleware does not hit `/uploads` that I tried. It's not really "static files", I guess.

A server-side ASP.NET solution for this is probably completely out of scope for Piranha, but maybe you'd know how it might be done from the top of your head?

**Comment by tidyui** [comment]
Hi again! Sorry for the slow response here. This is the code in the file storage that is responsible for creating the public url

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.Local.FileStorage/FileStorage.cs#L67

If you want a quick fix you can just copy this project, make your own version of the file storage provider and register this in your application instead. I'll add this as a feature request to the included provider as well for the upcoming release.

**Comment by tidyui** [comment]
Syntax for setting this up in application startup will be:

`options.UseFileStorage(naming: Piranha.Local.FileStorageNaming.UniqueFolderNames, generateVersionParam: true);`

**Comment by lukasan** [comment]
Thanks, turns out in my case there was no real issue, since, I think, etag is handled by a browser when a new file is uploaded and accessed via the same URI.

I tried hacking with Nginx to add no cache on `/uploads` path. Also injecting middleware to HTTP requests to return no cache. All that was not ideal. Also terrible for performance (instead of milliseconds for a PDF it became half a minute). Not to mention all media in blocks.

I'm glad something for improvement came out of this, though! Thank you for your responses.

Maybe even some sort of a configuration for which separate files to set `no-cache` to might make it to an enhancement request? 😄
