### ISSUE TITLE
Custom Manager views show non-admin menu

### ISSUE THREAD

**Issue by mohrtan** [PiranhaCMS/piranha.core#222]
I've customized the manager to extend it for additional data management. Works great except that the custom view contains the non-manager menu, i.e. the page map. I've tested a fix for this to use the full path when referencing the partial views in the Manager's _Layout.cshtml as noted below. There may be a better way (I'd like to use it if there is), but this worked for me.

In /core/Piranha.Manager/Areas/Manager/Views/Shared/_Layout.cshtml, instead of this:
        `@Html.Partial("Partial/_Menu")`

I did this:
        `@Html.Partial("~/Areas/Manager/Views/Shared/Partial/_Menu.cshtml")`

I did the same with all other partial views to ensure the correct views were included there as well.

**Comment by tidyui** [comment]
Hi there! Given the extra info in your [tweet](https://twitter.com/mohrtan/status/974392569009508352) the main issue is that you've put your custom admin functionality in another `area`. I've never really tested for that use case since I've always considered extensions to the admin belongs in the admin area. If I were to add a separate section for a specific customer group I would probably add this in a separate area.

Is there a specific reason for putting your admin functionality in a separate area?

**Comment by mohrtan** [comment]
I put it in the Manager area simple because that's where it lived in the app that uses the legacy version. I'm happy to put it where ever it needs to be to match your intentions. Are you saying that if I set my area to "admin" for the custom controller, this should work as designed?

**Comment by tidyui** [comment]
Yes it will probably work out-of-the-box. The problem with the menu is that `@Render.Partial()` looks for the partial view within the current area, that's why it can't find it. If you change your custom controllers/models/views to live within the `manager` area it will find the menu! You can always check with @gyretech, I know he has implemented a complete e-commerce system on top of the new Piranha manager!

**Comment by mohrtan** [comment]
I'm missing something. I think I've laid this out exactly as you indicated and I have the same menu as in the Tweet. I have uploaded this app to GitHub. Any insight you can give is appreciated.

[https://github.com/mohrtan/PiranhaTest]

**Comment by mohrtan** [comment]
Disregard - found the issue. Area names are case sensitive. Thanks for all your help.

**Comment by tidyui** [comment]
Great!!!
