### ISSUE TITLE
Add dictionary to site properties

### ISSUE THREAD

**Issue by AndreSteenbergen** [PiranhaCMS/piranha.core#234]
Would be nice to have key value pairs on sites, so an alternative css could be loaded, or another header images. etc.

**Comment by tidyui** [comment]
In Piranha 2.x the site can have its own PageType with site global regions & fields. I’m guessing adding that feature would solve this if I understand you right.

**Comment by AndreSteenbergen** [comment]
Is there documentation about how that should work? Or do you have a code sample? If I understand you correct, I think it does provide what I would like

**Comment by AndreSteenbergen** [comment]
Sorry, I read your comment the wrong way. It would be great to have that feature, and looking at the docs from legacy it is exactly what I mean, and defining it like PageType in a Model would open up endless possibilities. I don't have the time to make a contribution myself at the moment. But I love the way piranha works.

**Comment by tidyui** [comment]
I also started thinking about this issue in a completely different way. Let's say we'd introduce **theming** as a add-on package. A theme would have a definition class like, maybe something like this:

    [Theme(Id = "Blog", Title = "Fancy Blog")]
    public class BlogTheme {
        public enum ColorScheme {
            Light, Dark
        }

        public SelectField<ColorScheme> ColorScheme { get; set; }
        public StringField Title { get; set; }
        public ImageField Logo { get; set; }
    }

And maybe themes could be registered like this:

    // In ConfigureServices()
    services.AddPiranhaThemes();
    
    // In Configure()
    app.UsePiranhaTheme<BlogTheme>();

If the theme manager was installed and an active theme was selected the following view locations could be added to the `ViewEngine`.

    ~/Themes/<ActiveTheme>/Views/

This location would be inserted at the first location so that a `_Layout.cshtml` from this location would override the one in `~/Views/`. Also a new tab in the **manager config view** named `Theme Settings` (or something like that) where the fields specified in the current theme (in this case `BlogTheme.cs`) would be available.

For a custom site this would mean that you could include the theming package and create a theme for you application with the necessary global settings, but it would also give the possibility to just install theme packages into the application.

Of course given the nature of the framework and it's content type setup views will probably have to be written in a specific way for this to work, but that's details that can be ironed out later.

**Comment by AndreSteenbergen** [comment]
For themes I think it's nice. I like @tidyui idea more actually. It would make it possible to have multiple sites with the same code base functionality with perhaps some magic keys for an api, some secrets etc. Not just a theme.

**Comment by tidyui** [comment]
I'll make a new issue of it with a better title and link this one for reference! Then maybe we can get some more opinions on it as well!
