### ISSUE TITLE
Setup AppVeyor CI

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/piranha.core#27]
Setup AppVeyor (or another available build service) for automatically building & running tests. At the moment AppVeyor seems to have problems with building netcore 1.1 libraries/applications but it might be possible to set it up with custom config.

**Comment by TheWolfA2** [comment]
Have you tried changing the `global.json`'s version to `1.0.0-preview2-1-003177` as opposed to `1.1.0`? I found that Vs 2015 on my Windows computer is incapable of recognizing version `1.1.0` since the sdk folder contains the `1.0.0-preview2-1-003177`, but my Mac has absolutely no issue with recognizing `1.1.0`

**Comment by tidyui** [comment]
Yeah I actually had the same problem with the previous release of netcore for Win :)

https://twitter.com/tidyui/status/793040948037058560

For me, changing the folder name to the same as the name in global.json resolved the issue!

**Comment by tidyui** [comment]
The error is in the installation programs & how VS calculates the path when there's multiple versions of dotnet core installed!
