### ISSUE TITLE
Authentication problems after adding Piranha to existing project.

### ISSUE THREAD

**Issue by mfronczyk** [PiranhaCMS/piranha.core#313]
I've added the Piranha Identity package to my project and the CMS works fine. 

When I sign in on the main site, Piranha still wants me to login to the CMS Manager, which is perfect. But when I sign in in the CMS Manager, I become logged in on the main site as well but the authenticated user doesn't have the claims we use (which is obvious, because it comes from Piranha) and stuff breaks.

Is there a way to have 2 separate authentication schemes in a single project after adding Piranha to it? I'm wondering if it might be due to mistakes in our app, that we don't explicitly specify which authentication scheme to use and it uses a default one? Any help appreciated.

**Comment by tidyui** [comment]
I think the best way for you is to make your own implementation on Piranha.ISecurity so that it uses your current user & authentication. The manager just cares about claims, so as long as you can add these to your existing users you don’t need to schemes!

**Comment by mfronczyk** [comment]
Right, I read about it. However, I'd prefer to use the identity provided by Piranha, because then we can use the user management features you already provide. Our current sign in is for customers and I think it's better to separate them instead of signing in as a special customer who also has the Piranha claims.

**Comment by tidyui** [comment]
I haven't actually tried using two different schemes, so I can't really give any advice. However, when you find the solution, please share your findings as it is a good use case!

**Comment by tidyui** [comment]
The simple solution would of course be to add a base claim to all of the customers and check for that claim in the current web, instead of just checking if the current user is authenticated.

**Comment by tidyui** [comment]
I think I found an article that covers the concept with something called "Virtual Authentication Schemes".

https://medium.com/@joni2nja/dual-multiple-authorizations-using-virtual-authentication-schemes-in-asp-net-core-2-6d5a3140e41d

**Comment by mfronczyk** [comment]
Adding a base claim to all customers doesn't solve the problem, because the authorisation policies checked in Piranha use the default authentication scheme, so from our site, and the principal doesn't have the claims required by Piranha. So the effect is that I get stuck on the Piranha login form, even though that I'm signed in both in Piranha and our site.

**Comment by mfronczyk** [comment]
Virtual Authentication Schemes should work. So if I understand right, we should configure the virtual authentication scheme as the default scheme and use Piranha's scheme for urls starting with /manager (any other urls?)? What's the authentication scheme used by Piranha? I only found references to "Piranha.SimpleSecurity" in the code, but we don't use that.

**Comment by tidyui** [comment]
You can take a look at the code for the Piranha.AspNetCore.Identity package here:

https://github.com/PiranhaCMS/piranha.core/tree/master/core/Piranha.AspNetCore.Identity

Also, if you find that it would simplify setup by making more stuff in the identity package configurable, just add a PR with the additions and I’ll make sure it’s included in the next release!

Regards

**Comment by mfronczyk** [comment]
Thanks for help. I'll have a look, but I'm actually leaning towards deploying the CMS manager as a separate project/site and just add the core Piranha packages to the main site to fetch the content.

**Comment by tidyui** [comment]
I'll test the Virtual Authentication schemes next week and see if I can come up with anything. Deploying the manager as separate site is fully possible **BUT** in order to the get the cache to work properly you would need to use a distributed cache, something that we don't have a package ready for yet. This means you would have to write your own cache service.

**Comment by mfronczyk** [comment]
I looked a bit at the authentication and it seems that AddIdentity() does quite a lot of stuff, for example sets the default authentication scheme, which means that calling AddPiranhaIdentity() might have big impact on the whole site and the order matters. Maybe calling AddIdentityCore() would be enough? I'm wondering how would it work with a site that already uses identity... (we aren't).

Thanks for the heads up about the cache. We'd have to do it anyway, because our site is run on multiple servers already.

**Comment by tidyui** [comment]
The identity module is really intended for new sites that doesn’t have an existing authentication set up. If you have Identity the preferred way is to integrate piranha with the existing authentication mechanism.

**Comment by shannondhill** [comment]
Hi Hakan.  I also wanted to pose a question along the same lines as this one since I am having trouble integrating PirahnaCMS into an aspnetzero Angular/WebApi application that uses an existing authentication scheme.  My project already has IdentityServer integrated, so I thought it best to remove the line

`services.AddPiranhaIdentityWithSeed<IdentitySQLiteDb>(options => options.UseSqlite("Filename=./piranha.db"));`

based on your recommendation above that the identity module is only intended for sites that don't have an existing authentication set up (mine does).

However, what I am seeing is that some of functionality in the identity module seems to be required, even when not using it directly.  Namely, I receive the error "The Authorization Policy named: 'PirahnaRoles' was not found." when loading my application.  If I add that line back in, my app complains that multiple Identity Providers are registered.

Can you please let me know if I'm thinking about this correctly or if I should be looking at this from a different angle?  My plan is to update the routing in my application to send allow "/manager" requests to the Piranha Manager (I'm hoping I can figure out how to do that :) and to create methods in  my WebApi to return data from Piranha based on the incoming URL in Json format.  Seems pretty straightforward, right?  Thanks for any help you can provide!

**Comment by tidyui** [comment]
I'm guessing you still have the NuGet-package `Piranha.AspNetCore.Identity` installed in your project! Since MVC auto discovers Controllers it finds the **admin controllers** for the identity module in your project which uses the policy you mention, however you have removed the line that actually adds the policy!

If you remove the Piranha identity packages completely the error should go away.

Best regards

Håkan

**Comment by shannondhill** [comment]
Ah ah!  As you can tell, I'm relatively new to MVC and .Net Core.  :)  Thanks for your help!  I hope to be able to provide some guidance for other other folks looking to integrate AspNetZero and Piranha once I'm all done.  Thanks!

**Comment by shannondhill** [comment]
Hello again, Hakan.  I'm curious if there's an equivalent to the old setting "passivemode" in the new .Net Core version?  The routing for my applicated seems to be being overridden by Piranha.  Is there a way to enable passivemode in the current iteration?  Thanks!

**Comment by tidyui** [comment]
Well in `AspNetCore` it's all about middleware. The default template calls:

    app.UsePiranha();

in `Startup.Configure` which enables all of the available middleware. If you want to you can enable the different middleware one by one, take a look at the **wiki** here:

https://github.com/PiranhaCMS/piranha.core/wiki/Middleware

Also, I'm closing this issue as there's too many questions mixed up in one thread. If anyone participating has specific questions, open a separate issue for each question.

Best regards
