### ISSUE TITLE
Change url for admin area

### ISSUE THREAD

**Issue by amh2013** [PiranhaCMS/piranha.core#378]
Just wondering what would be the quickest way to change admin url for security and other purposes.  Or move the admin to different location.

**Comment by tidyui** [comment]
The `/manager` route is not configurable at the moment. It is fully possible to deploy the manager interface to another location, in `Startup.cs` this is the line that activates the manager interface:

    services.AddPiranhaManager();

The only thing to keep in mind is when using a **cache**. The built in **MemCache** caches data in process memory on the web server, this will not work when deploying the manager to a different location as cached pages on the website won't be purged from cache when updated or deleted by the manager interface on the other site.

To get this to work properly you'll have to implement the interface `Piranha.ICache` using a distributed cache so both applications (or servers) uses the same instance of the cache.

Best regards

**Comment by amh2013** [comment]
So the AddManager has options?  Also the example is what we used to build the site.  Which means CmsController handles the pages.  I believe it would be a good idea to have other examples how to use a custom controller without configuring the standard cms controller.  Again the lack of examples limits the use of the cms, maybe you can point to an example where the cms is used in existing application, as the documentation does not give too much details.

**Comment by amh2013** [comment]
@tidyui  I understand and thank you.  I will do that and hope it can help you.

**Comment by sobomp3** [comment]
I figure this is probably the best place to post this followup question. I was finally able to add the Piranha CMS 7.1 packages to my existing MVC Core App in order to add simple blog functionality to my website. The app already uses Identity to handle User registration/management.

At the moment I'm just using Simple Security to avoid conflicts with Identity. The SQL Database tables get created upon initial run (coexisting just fine with the existing database tables), and I was able to Seed it with some old Seed code from one of your sample projects. Going to /blog/archive and /blog/post works great. However, if I attempt to go to localhost:xxxx/manager, things break. It looks like Identity is catching this and isn't liking something, as it redirects to url: localhost:xxxxx/Identity/Account/AccessDenied?ReturnUrl=%2Fmanager

Is there still no way to configure manager to use another route? I'd love to just have it at /blog/manager. 

Any ideas?

**Comment by tidyui** [comment]
Hi there! I think the best solution for you would be to implement your own Piranha.ISecurity using your current identity implementation. As long as users have the correct claims they will be able to access the manager!

We have not investigated further on making the admin url configurable, but we are open for pull requests :)

**Comment by sobomp3** [comment]
Hi there,
Thanks for your reply awhile back.

I'm going to preface this with the fact that I have very little Microsoft
Identity experience. In our application, we have Identity up and running
returning a user object that inherits from the Microsoft IdenitityUser
object (just adds some extra fields). I've been struggling for weeks trying
to get Piranha CMS into our project to just allow our site administrators
(User.Administrator == true) access to adding/editing a simple blog.
Archive and Posts work great. Trying to get to /manager always bombs.

You mentioned implementing Piranha.ISecurity in your last email to me, but
I find the documentation on this page:
http://piranhacms.org/docs/extensions/authentication

to be a bit lacking. The line "services.AddSingleton<Piranha.ISecurity,
MyCustomAuthService>()" doesn't really give me many answers. What would
"MyCustomAuthService" look like in this case?

In the end, I need the simplest thing - three of our users just need to be
able to add/edit blog posts.

:)

Thanks,
Chris

**Comment by tidyui** [comment]
Hi! The service needs to implement the ISecurity interface described in the same page, and it’s three methods Authenticate, SignIn and SignOut.

After that is done the signed in user will need the correct Claims to access the different parts of the manager. All of the claims used are described here:

http://piranhacms.org/docs/architecture/authentication

Best regards

**Comment by tidyui** [comment]
You can also look at our implementation of ISecurity for Identity. You can see that the complexity for signing in and out is fairly low.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore.Identity/IdentitySecurity.cs

Regards
