### ISSUE TITLE
I want to add fields

### ISSUE THREAD

**Issue by ayzhanglei** [PiranhaCMS/piranha.core#382]
I want to add fields，But i don't know how to Add-Migration

**Comment by tidyui** [comment]
Hi there! 

We don't support or endorse that you add database fields through the DbContext as this will pretty much eliminate all possibilities of you updating to a newer version later on. What kind of fields are you missing and on what entity? If it's something general it's better to open an issue so we can add it the general version, if it's specific maybe there is a way for you to add it in a different way as the **region** and **field** abstractions provide great flexibility for designing data-structures.

Best regards

Håkan

**Comment by ayzhanglei** [comment]
I want to add some information to users, such as gender, age, and comment function.

**Comment by tidyui** [comment]
Ok. Since the user module is separate from the core you can extend it and create your own user module without any problems. The migrations are created in the provider project, for example `Piranha.AspNetCore.Identity.SQLServer`. The new dotnet CLI is a bit tricky when adding migration to a library, you'll need to specify a **startup** project and which **context** to migrate as there will be several DbContext's available. Use the following syntax (*note this is an example where you want to add a migration called AddUserFields for SQLServer*).

    dotnet ef migrations add AddUserFields --startup-project ../../examples/CoreWeb --context Piranha.AspNetCore.Identity.SQLServer.IdentitySQLServerDb

Regards

**Comment by ayzhanglei** [comment]
Okay, thank you
