### ISSUE TITLE
Question: Piranha updates

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#430]
Hello!

This is quick question - @tidyui  can you give us an approximate date of releasing **5.3** and more importantly **6.0** versions of `Piranha CMS`?

I am just eager to see the changes, but the projects in this repository had no update for about 2 weeks.

Best Regards,
Chris

**Comment by tidyui** [comment]
Hi there! We've basically spent the last two weeks investigating if we can use **server-side Blazor** (which will be a part of .NET 3.0 as `Razor Components`) when building the new manager interface which is why it's been kind of quiet. Version `5.3` is almost ready and be released shortly, regarding `6.0` we will have to make a decision on how it will be implemented. 

If we were to decide that Razor Components would greatly improve the richness of the interface this means that it probably won't be released until Q1 2019 as this is the release plan for .NET 3.0 (or at least so I think). If we decide that we continue with the current MVC-version of the new interface it might be ready sooner. 

We'll see if we can increase our transparency by communicating release dates here at GitHub.

**Comment by aneff-official** [comment]
Hi!

I am really amazed by your fast responses - thank you for that. About the versions:
- 5.3 - Shortly meaning next week?
- 6.0 - If this is the better solution overall, my vote is for this new thing "Blazor". I am not sure what kind of tech is it, but I guess it may be worth having a look at it. The question here is other - are you freezing all updates until it comes out or could it be used for a later version? Also, you have a lot of things moved from 5.3 -> 6, meaning some of them might already be finished.

P.S. It is a good idea to actually have some way of indicating when (approximately) the next release date is.

Yours,
Chris

**Comment by tidyui** [comment]
If we were to make a technical choice for `6.0` that would push the release date into the future it's likely that some functionality would be moved in to a `5.4` & `5.5` that will be developed in parallel. The biggest overall effort in `6.0` is the manager interface, so this means that other more core related features could very well be moved into minor releases.

**Comment by aneff-official** [comment]
Hey

I see now, thanks a lot again.

Chris
