### ISSUE TITLE
Adding a region to page is not backward-compatible

### ISSUE THREAD

**Issue by mpawlus** [PiranhaCMS/piranha.core#446]
Adding a new Region to an existing Page causes a NullReferenceException during deserialising if the change is not pushed to the front-end that uses the CMS, whether the region has any value set or not.

Adding a new Region should be transparent for the front-end.

Here's an excerpt from the stack trace:
```
System.NullReferenceException:
   at Piranha.Services.ContentService`3.SetSimpleValue (Piranha, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null)
   at Piranha.Services.ContentService`3.Transform (Piranha, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null)
   at Piranha.Repositories.PageRepository.GetBySlug (Piranha, Version=5.2.1.0, Culture=neutral, PublicKeyToken=null)
```

**Comment by tidyui** [comment]
Give me some more information about your setup! Are you deploying the admin to a different web application/site than the client, and if so which part of the application is responsible for updating the content types using the `AttributeBuilder`. 

Since your front-end is not aware of the model change I'm assuming the admin project is responsible for updating the models in the database?

Best regards

**Comment by mpawlus** [comment]
Thanks for the quick fix. When can we expect version 5.3.1?

**Comment by tidyui** [comment]
We have some issues left to fix before release but we could deploy a preview package.

**Comment by tidyui** [comment]
This has now been deployed to NuGet.. We were delayed due to various reasons

**Comment by mpawlus** [comment]
OK, we'll give it a try when we can. Thanks!
