### ISSUE TITLE
Last Modified

### ISSUE THREAD

**Issue by mpjones84** [PiranhaCMS/piranha.core#453]
How do you view the last modified date of a field?  If not what is the best way to achieve this for a field or block?

**Comment by tidyui** [comment]
Hi there! This information is not available on field level. Due to how the internal change tracker of `Entity Framework` works it would be impossible to provide a reliable Last Modified for fields without comparing all data before saving. Last Modified is available on the main content objects.

* Blocks
* Pages
* Posts
* Sites

Best regards

**Comment by mpjones84** [comment]
Thank you for the quick response, I have an object that I wish to track

`        private static string salaryFormat = "£###,####";
        public Guid Id { get; set; }
        public string DirectLinkEncoded { get; set; }
        public string DirectLink { get; set; }
        public string Teaser { get; set; }
        [Field(Title = "Reference")]
        public StringField Reference { get; set; }
        [Field(Title="Title")]
        public StringField Title { get; set; }
        [Field(Title = "Location")]
        public StringField Location { get; set; }
        public string Package { get; set; }
        [Field(Title = "Min Salary")]
        public NumberField SalaryMin { get; set; }
        [Field(Title = "Max Salary")]
        public NumberField SalaryMax { get; set; }
        [Field(Title = "Salary Benefits")]
        public StringField SalaryBenefits { get; set; }
        [Field(Title = "Job Spec sheet")]
        public DocumentField Document { get; set; }
        public string DocumentUrl { get; set; }

        public bool IncludeInEmail { get; set; }`

This is stored in a list on the page, is the best way to store a date on the object, if so how do I capture when it has changed (not to worry if it is not possible), or just when it was created.

Thanks again

**Comment by tidyui** [comment]
Well the problem lies in the fact that probably **all** fields will be updated (even with the same data) in the database whenever the page is saved, at least this is how the change tracker of Entity Framework as always worked in the past with related objects.

When you say you want to track when the object is changed, I'm assuming your want to track when a **field** on a specific **item** in the list is changed. This means that you really want to the DateField to reflect when some of the other fields have been updated, right?

On possibility is that you create your own fields that enable tracking in the manager, for example

    public class TrackedStringField : StringField { }

You could then add some specific class, container or whatever you see fit in your `EditorTemplate`.

    @model TrackedStringField

    <div class="tracked-field">
        // Copy markup from original field
    </div>

Then inject some javascript into the manager to actually update the DateField on the item whenever one of the tracked fields are changed.

**Comment by mpjones84** [comment]
To be honest any field within the object, its just to say the Job was last updated.  You suggestion makes sense though, I will give it a go.

Thank you.
