### ISSUE TITLE
ICache/MemCache vs IMemoryCache/MemoryCache

### ISSUE THREAD

**Issue by 3x0dv5** [PiranhaCMS/piranha.core#468]
Hi, quick question. 
Why did you go with your own version if ICache and not use the interface defined in Microsoft.Extensions.Caching.Memory?

https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryCache.cs
https://github.com/aspnet/Extensions/blob/master/src/Caching/Abstractions/src/IMemoryCache.cs

actually maybe it would be even better if instead of your implementation or even IMemoryCache you would use IDistributedCache that can be used for both in memory cache and for actual distributed cache
https://github.com/aspnet/Extensions/blob/master/src/Caching/Abstractions/src/IDistributedCache.cs

For memory cache you can use this 
https://github.com/aspnet/Extensions/blob/master/src/Caching/Memory/src/MemoryDistributedCache.cs
and for distributed caching here is an implementation on redis as well
https://github.com/aspnet/Extensions/blob/master/src/Caching/StackExchangeRedis/src/RedisCache.cs

then in your startup you just need to add the already existing
services.AddDistributedMemoryCache();

An example of usage with caching into a sqlserver db
https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-2.2

**Comment by tidyui** [comment]
That's a relevant question. 

To simplify the code I wanted a **single interface** to perform cache operations on rather than support different paths (`IMemoryCache` / `IDistributedCache`). This way it would be possible to create a cache provider that operates on an injected `IMemoryCache` object, and another one that operates on an injected `IDistributedCache` object without having to know which it is in the source code.

**Comment by 3x0dv5** [comment]
Thanks for taking the time to go over my question.
Fair enough. But for future maybe it wouldn't be such a bad idea to use IDistributedCache, and then use the MemoryDistributedCache (it will just behave similarly to your current memcache) but it would also allow you to quickly plug distributed cache to either Redis or SqlServer and will allow you to use settings available in .netcore like expiration.

**Comment by tidyui** [comment]
I have added support for using `IMemoryCache` or `IDistributedCache` with Piranha. The cache service for `IMemoryCache` works with the currently released version, you can just copy the source code and add to your project until released if you want. Using `IDistributedCache` however requires updates marking a lot of classes as `Serializable`, so that won't work until the next release.

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Cache/MemoryCache.cs
https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha/Cache/DistributedCache.cs

Best regards
