### ISSUE TITLE
HTML is stored escaped

### ISSUE THREAD

**Issue by wireless-r** [PiranhaCMS/piranha.core#469]
Hi. I'm trying to store HTML code by a custom block with an HtmlField. The code becomes escaped when it is stored in database:  `&lt;b&gt;Test&lt;/b&gt;`

I want it to be stored as HTML: `<b>Test</b>`

```cs
[BlockType(Name = "Code", Category = "Content", Icon = "fas fa-code")]
public class CodeBlock : Block
{
	/// <summary>
	/// Gets/sets the html body.
	/// </summary>
	public HtmlField Body { get; set; }
}
```

**Comment by tidyui** [comment]
Thanks! Now I know what you want to achieve, and why it's not working like you want it to!

When typing content into a `contenteditable` element it's assuming you want the content your writing is the content your want displayed. In order to display the HTML-code (and not render it as HTML-content) it has to be escaped, so your web browser does this for you. As you want the possibility to embed custom HTML-code on your page, I would change it to the following markup for the `EditorTemplate`. With these classes you'll get the right look n feel, auto grow on the textarea and it will render as HTML in the web application.

**Areas/Manager/Views/Shared/EditorTemplates/CodeBlock.cshtml**

    @model PiranhaTest.Models.Blocks.CodeBlock

    <div class="form-group single-region">
        @Html.TextAreaFor(m => m.Body.Value, new { @class = "form-control raw-text" })
    </div>

Best regards

Håkan

**Comment by wireless-r** [comment]
Thank you
