### ISSUE TITLE
Repository classes constructors take implementation instead of interface

### ISSUE THREAD

**Issue by wireless-r** [PiranhaCMS/piranha.core#474]
Hi. I discovered that most repository classes take the interface `IApi` as constructor parameter, while some take the implementation `Api`.

Example:

```cs
public CategoryRepository(Api api, IDb db, ICache cache = null)
```

It's inconvenient when one wants to inject a custom implementation of `IApi`. The repositories in question are `AliasRepository`, `ArchiveRepository`, `CategoryRepository`, `MediaRepository` and `SiteRepository`.

Also not sure why ArchiveRepository's constructor has `internal` access modifier, which is inconvenient for instantiation in the custom api.

**Comment by tidyui** [comment]
The reason is that some repositories are not 100% isolated in the way that they get data from other places directly for performance reason. We can take a look at the individual instances where the constructor takes in an actual object reference instead of an interface to see why.

What parts of the interface do you want to replace, what are you looking to achieve. It's always best to focus on the task at hand.

We've also been looking at splitting the repository layer into two different layers, one service layer handling all of the logic and one pure data repository layer. The reason of course being to be able to change data storage completely but keep all data validation and logic in the services (or the other way around).

Best regards

**Comment by tidyui** [comment]
Hi there! We’ve done the same, created a product module based on the content classes using the content service for transformation and it all works, however these are my recommendations:

1. Never extend the Piranha DbContext (Not sure if you’ve done this). This will most likely break all future Piranha migrations.
2. Don’t extend the included api, create your own api, this way you can package your new functionality in an isolated module that you can reuse (or make available online).

Best regards

Håkan
