### ISSUE TITLE
Manually re-order the Blog Archive posts?

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#505]
Hi there,

I was wandering if is it possible to re-order posts of a blog page?

Kick-Ass Option #1
A drag-and-drop re-ordering mechanism as in site's pages? (That would be a major revision I suppose 😃)
I can create the javascript part but "how to save it" is the question.

Simple Option #2
Adding a number field to each posts (That I can do with fields) then order them to that numbers value ASC/DESC? (This I have no clue how)

**Comment by tidyui** [comment]
Hi there! The main concept with archives is the fact that it’s automatically ordered. If you want a structure you can order manually, use pages instead.

Regards

**Comment by clientwestwood** [comment]
@tidyui Fair enough.
Off-the-record, is there any hack do you recommend like adding a number field to each posts then order them to that numbers value?

**Comment by stamminator** [comment]
I believe blog posts are ordered by publish date, descending. Since this is an editable field, you should be able to use it for reordering. Disclaimer: I do not know if there are any SEO implications for artificially changing a post's publication date, especially if you're using the date in your slug.

**Comment by clientwestwood** [comment]
@stamminator thank you :D
