### ISSUE TITLE
Multiple Blocks with Archive listing slow down page

### ISSUE THREAD

**Issue by clientwestwood** [PiranhaCMS/piranha.core#519]
Hi there!

I have a Block that list specific Archives. (Thanks to @tidyui - #493)
I use it to list different Archives in a single page.

After I add 3-4 of this Block in a page, loading time slow down tremendously.
Is there a solution for that?

_By the way I use "Piranha.Cache.CacheLevel.Full" but it seems to not relate to this issue._

**Comment by tidyui** [comment]
Well, are you loading posts for these 3-4 archives you've added to your page? Because if you are, you are in fact:

1. Loading the requested page (will get cached)
2. Loading the pages referenced in the blocks (will get cached)
3. Loading x number of posts, y number of times (will get cached partially)

There's also a lot of models being transformed in order to get all of these data. If this is the way you've implemented it my recommendation is using the build in features for caching data server side (without sliding expiration) and cache the posts for all archives for a certain amount of minutes.

**Comment by w0ns88** [comment]
Is there a way to load an archive and its posts without the blocks and fields within it. Because currently when I load an archive, it loads everything else too, which might get quite heavy depending on the blocks of each posts. Even with caching and pagination, I think the ability to fetch an archive without post block would be great. I don't know what you guys think? Maybe it is only useful in my use case?

**Comment by tidyui** [comment]
Hi there @w0ns88! There are two special model types available for loading content without regions & blocks, **PageInfo** & **PostInfo**. Unfortunately you can’t say which type you want to load the posts in in the ArchiveRepository. We can add this for the next release, we’re planning on releasing a first alpha pretty soon.

Regards

**Comment by w0ns88** [comment]
@tidyui thanks for the info. Yes it would be cool to be able to fetch an archive with **PostInfo** instead of **Posts**. One more thing that would be awesome is to fetch an archive with posts that include the **Regions** but not the **Blocks/Fields**. Again, this is maybe only useful for my case.

**Comment by tidyui** [comment]
I totally understand your use-case. We've discussed in the past if we should implement something we referred to as **projections**, i.e a class containing a subset of regions/blocks. You could then register this class as a projection of a certain model type.

Loading it from the database would result in only getting the values for regions you've specified.

It's a lot more generic (and of course complex) than your use case, but something that would be very useful when fine-tuning performance for bigger projects.

Regards
