### ISSUE TITLE
Angular, Vue OR React frontends.

### ISSUE THREAD

**Issue by asadsahi** [PiranhaCMS/piranha.core#546]
I am trying to build frontends in Angular, Vue and React as an experiment. Saw some discussion around this area before https://github.com/PiranhaCMS/piranha.core/issues/325. But can't find if something available as API as of now for a JS based frontend to fetch data.

@tidyui you mentioned in that thread that this is easily available and you shared a working example of api, in a feature branch but can't get that link (https://github.com/PiranhaCMS/piranha.core/tree/features/webapi-module/core/Piranha.AspNetCore.Api) working.

Can you please suggest an approach if this is achievable? Happy to work together on this one to put an example in this repo.

**Comment by w0ns88** [comment]
Hi @asadsahi he has an example of an Angular frontend here:
[https://github.com/PiranhaCMS/piranha.core.angular](https://github.com/PiranhaCMS/piranha.core.angular). Hope this helps.

**Comment by tidyui** [comment]
The reason for not providing a default api package is:

1. It's extremely easy to put together your own
2. Even with massive setup & config options it would be hard to match everyones whites

If you take a look at the example projects the exact same rule applies **but** instead of returning `View()` from your actions, just return `Json()`. One difference would be that you don't really need one action per view, rather you could use one action per level of authentication and use the **route** attribute for controlling authentication level per page/post as described in this post:

http://piranhacms.org/blog/techniques-for-securing-pages

An api controller could be as simple as this:

    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Piranha;
    using Piranha.Models;
    using Piranha.Services;

    namespace MvcWeb.Controllers
    {
        public class CmsApiController : Controller
        {
            private readonly IApi _api;

            /// <summary>
            /// Default constructor.
            /// </summary>
            /// <param name="app">The current app</param>
            public CmsApiController(IApi api)
            {
                _api = api;
            }

            /// <summary>
            /// Gets the blog archive with the given id.
            /// </summary>
            [Route("archive")]
            public async Task<IActionResult> Archive(Guid id, int? year = null, int? month = null, int? page = null,
                Guid? category = null, Guid? tag = null)
            {
                var model = await _api.Pages.GetByIdAsync<Models.BlogArchive>(id);
                model.Archive = await _api.Archives.GetByIdAsync(id, page, category, tag, year, month);

                return Json(model);
            }

            /// <summary>
            /// Gets the page with the given id.
            /// </summary>
            [Route("page")]
            public async Task<IActionResult> Page(Guid id)
            {
                var model = await _api.Pages.GetByIdAsync<PageBase>(id);

                return Json(model);
            }

            /// <summary>
            /// Gets the restricted page with the given id.
            /// </summary>
            /// <param name="id">The unique page id</param>
            [Route("pagerestricted")]
            [Authorize(Policy = ...)]
            public async Task<IActionResult> PageRestricted(Guid id)
            {
                var model = await _api.Pages.GetByIdAsync<PageBase>(id);

                return Json(model);
            }

            /// <summary>
            /// Gets the post with the given id.
            /// </summary>
            /// <param name="id">The unique post id</param>
            ///
            [Route("post")]
            public async Task<IActionResult> Post(Guid id)
            {
                var model = await _api.Posts.GetByIdAsync<PostBase>(id);

                return Json(model);
            }
        }
    }

You'd probably want to add some endpoints for exporting the `Sitemap` as JSON for rendering menus and such.

Best regards

Håkan

**Comment by tidyui** [comment]
As a side note, I don't manage the Angular example, that is handled by @jcphlux. The repo will most likely be moved to his profile to avoid confusion.

/Håkan

**Comment by tidyui** [comment]
Closing as question has been answered

**Comment by apunekar** [comment]
> Hi @asadsahi he has an example of an Angular frontend here:
> https://github.com/PiranhaCMS/piranha.core.angular. Hope this helps.

link not available

**Comment by tidyui** [comment]
@apunekar As we didn’t have time to maintain  this repository was transferred back to the user who contributed it. Unfortunately he didn’t maintain it either and it even looks like he has deleted his GitHub account.

I found a fork of his repository, but since it hasn’t been updated since 2018 it’s not really up to date.

https://github.com/droyiii/piranha.core.angular

Regards
