### ISSUE TITLE
How can you query the page data?

### ISSUE THREAD

**Issue by runxc1** [PiranhaCMS/piranha.core#611]
So I am just playing around with piranha.core and so far I really like the editor and find it it very nice in being able to create content but there really isn't any way to query that content.   I am creating widget with 10 or so fields and on the start page want to show the 3 most recent widgets that are still for sale for example.  It seems the only way to model this is to create a page add a region, use the api to get all pages and then I assume I can filter those once I cast them to the correct page type.   It kind of makes sense that the Widgets are each WidgetPages but it seems very limiting to get a subset of pages based on any criteria.   Am I missing something?

**Comment by tidyui** [comment]
Hi there! Since data storage is abstracted it’s very hard to provide a generic search strategy through the high level api that would be efficient on all setups. If you’re using EF, my suggestion is that you:

1. Inject a Piranha.IDb in your code besides the basic IApi you already have.
2. Query the database any way you want and select the **Id** of the matching pages.
3. Load the pages through the Api using GetById

Given that you have some form of caching enabled in production at least GetById will in most cases return the model straight from cache.

Best regards!

**Comment by tidyui** [comment]
Closing as question as been answered
