### ISSUE TITLE
Collapsing/hiding blocks

### ISSUE THREAD

**Issue by patrickdemooij9** [PiranhaCMS/piranha.core#613]
Currently you are only able to collapse block groups, however the functionality would be so great in normal blocks too. If I even have 1 large block, it takes up most of the space on the screen. I would suggest adding collapsing blocks and every block starting collapsed at the start.

**Comment by tidyui** [comment]
Hi there. The main idea of blocks are that they should contain smaller sections of information, so that the editor can easily change the disposition of a page. I'm assuming you have a `HtmlBlock` with lots of content in it, if this is the case our recommendation is that you split the block in to several smaller blocks so you can control it better.

For example, in the block editor provided by `Ghost` the Html Editor is intended only for a single paragraph, and a new block is automatically created when you hit enter.

As the main concept of blocks is to give the editor a good overview of how disposition of the page looks we will most likely not add support for starting page edit with collapsed blocks as this would default the purpose.

Best regards

**Comment by patrickdemooij9** [comment]
I agree with your point that blocks should be as small as possible and that's something I am doing right now. However, there is no limit on how many blocks can be placed on the page itself. So let's take a look at my current page. It consists of the following blocks:

-Carousel: BlockGroup, where the block inside has 3 fields: Image, Title (stringfield) and text (stringfield).
-Introduction: Consisting of Title (Stringfield), SubTitle (Stringfield) and Body (TextField).
-Inventory (Basically multiple images with links): BlockGroup, where the block inside has 2 fields: Image and url.

Now, with only this I will most likely fill up my entire screen with a lot of information even though my blocks are very small. There is just too much information showing to easily work with it.
Or am I using blocks wrong here? Is there something else I should be using instead of this.
