### ISSUE TITLE
How to show breadcrumb navigation above post or page?

### ISSUE THREAD

**Issue by zareiramin** [PiranhaCMS/piranha.core#660]
Hi, 

Does piranha supports breadcrumb like navigation? if yes, how we can show it above post title.

**Comment by tidyui** [comment]
Hi there! Rendering a breadcrumb is very much like rendering a menu, i.e. looping over the sitemap that you can get by calling `WebApp.Site.Sitemap` in your `.cshtml` view. Take a look at the partial view rendering the menu in the example. https://github.com/PiranhaCMS/piranha.core/blob/master/examples/MvcWeb/Views/Shared/Partial/_Menu.cshtml

The big difference, since you want a recursive method for rendering the items is that you probably need a `DisplayTemplate` rendering the item and it's children if it's selected.

Regards

**Comment by zareiramin** [comment]
Dear tidui,

What is the purpose of Piranha.Models.Structure.GetBreadcrumb()?
Since BlogPost has property Category of Taxonomy type, we can not navigate to parents. And we should add some property to it that represents hierarchy of post.

**Comment by tidyui** [comment]
Right, I totally forgot about `GetBreadcrumb()` that method as already done the recursive part I mentioned. The purpose of rendering a breadcrumb for a post is that all posts are positioned below a certain Archive Page, and you can have several archives in a site. Let's say you have a product page in your site positioned at:

    /products

Then you have an archive page with the product news at:

    /products/product-news

And posts would then be located at:

    /products/product-news/meet-our-new-product

A valid breadcrumb for this post could be:

    Products / Product News / Meet Our New Product

Best regards

**Comment by tidyui** [comment]
So to clarify, the `GetBreadcrumb` method **always** takes a **Page Id** as argument. For a post this would be the id of it's Archive Page parent.

**Comment by zareiramin** [comment]
It worked.  however i want something a bit different.
suppose that i have a `post `in a blog with some `category `assigned to it. i need a breadcrumb like below:

>  blog / category 1 / sub-category 12 / post title 

I've modified the category model so a category may have a parent category.

**Comment by tidyui** [comment]
Ok, I can't really help you with that since Piranha doesn't have subcategories.

Regards
