### ISSUE TITLE
[BUG] Regions Lists

### ISSUE THREAD

**Issue by aneff-official** [PiranhaCMS/piranha.core#690]
Hi

I think this is either a strange behaviour or even a bug. When you have the following:
![2019-06-28 11_30_50-Window](https://user-images.githubusercontent.com/32654709/60336523-8069b200-9998-11e9-974a-88c912f75525.png)

`ListExpand` = false, some of my custom fields are not editable.

Another thing is, that when specifying `ListTitle` - is it intended to require the **[Field]** attribute to work? Couldn't it just work with a normal
`public string Title { get; set; }` ?

It could be just me or my mouse, because I couldn't reproduce it, but in the regions IList<CustomClass1> and IList<CustomClass2>
for some reason adding new item added 2 or 3 more.

Cheers,
Chris

**Comment by tidyui** [comment]
Hi there! You first issue with non-editable fields, it's very hard to assist you if you have custom fields with custom views in the manager. The only difference with `ListExpand=false` is that the fields are shown directly in the list header instead of in the collapsible body.

As for the ListTitle it currently only works with **Fields** and not with regular properties, this is due to how it's currently implemented.

The last section I didn't quite follow you, so if you have question I haven't answered, please clarify them and I'll do my best.

**Comment by aneff-official** [comment]
Hi

You did answer correctly. Just for the first issue I am not using custom fields and when it's not collapsible body you can't really press on the editor for `HtmlField`.

I found the solution for the last issue that I had. It sounds really vague, because somehow I must've deleted parts of what I had written.

P.S. Should I change the title not to include [BUG}?

BR
Chris

**Comment by tidyui** [comment]
No it's ok :) In the future you don't need to add it in the title, we will label the issue depending on what it is as soon as we read it!

Best regards
