### ISSUE TITLE
Advance routing for ArchivePage as Child of a Page

### ISSUE THREAD

**Issue by gyretech** [PiranhaCMS/piranha.core#699]
So I have a page 
```
[PageType(Title = "Slug page", UseBlocks = false)]
[PageTypeRoute(Title = "Default", Route = "/slugpage")]
public class SlugPage : Page<SlugPage>
{        
  ......
}
```

So I created a page /page-slug

Now I want a page /page-slug/slug-archive So I created the following

```
[PageType(Title = "Slug archive page", UseBlocks = false)]
[PageTypeRoute(Title = "Default", Route = "/slugarchive")]
public class SlugArchivePage : ArchivePage<SlugArchivePage >
{
  ....
}
```
But what I get is: Page "/page-slug/slug-archive" cannot be found. With the following output.

```
info: Piranha.AspNetCore.PageMiddleware[0]
      Found page
  Route: /slugpage/slug-archive
```

It is obviously looking for the archive page under the page route. How do I resolve this.

**Comment by tidyui** [comment]
Have you created the page `slug-archive` below `slug-page` in the sitemap?

Regards

**Comment by gyretech** [comment]
Yes I did. slug-archive is a child of slug-page.

- Keshwar

________________________________

**Comment by tidyui** [comment]
Ok. I can see from the info printout that it doesn’t find your archive page, it finds “slug-page” and thinks “slug-archive” is an extra route param which it passes along. As your action doesn’t accept it MVC throws 404. Have you double checked the slug of the archive so it contains the “slug-page/“ prefix?

**Comment by gyretech** [comment]
Yes I triple checked.

- Keshwar

________________________________

**Comment by gyretech** [comment]
If I create a non-archive page under slug-page, that page works just fine.

- Keshwar

________________________________

**Comment by gyretech** [comment]
Also I forgot to mention that I am using Razor Pages.

**Comment by gyretech** [comment]
You can actually replicate this behavior in one of your examples. Simply move “blog” under features, then edit blog so that the slug updates to “features/blog”. Then try to access “/features/blog” then you will get Page Not Found.

**Comment by tidyui** [comment]
Hi again @gyretech!

I can see from the code that the standard setup will produce the exact error you're getting. The reason for this is that the `PageRouter` intercepts the parent page before the `ArchiveRouter` gets the chance to identify the child archive. The provided middleware (in the default order) just isn't capable of finding an archive page located below a regular page. To fix this in your project. let's take a look at what the extension method `AddPiranha` does:

    public static IApplicationBuilder UsePiranha(this IApplicationBuilder builder)
    {
        return builder
            .UseMiddleware<Piranha.AspNetCore.ApplicationMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.AliasMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.PageMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.PostMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.ArchiveMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.StartPageMiddleware>()
            .UseMiddleware<Piranha.AspNetCore.SitemapMiddleware>();
    }

The problem here is that the `ArchiveMiddleware` is positioned **after** the `PageMiddleware` in the pipeline. Instead of calling this method, call the appropriate extension methods for adding all of the desired middleware in the order your need, in your case `ArchiveMiddleware` before `PageMiddleware`. To clarify, this will disable the possibility to add a regular page below an archive page.

Best regards

Håkan

**Comment by tidyui** [comment]
Btw @gyretech did you have a PR for this, because you solved it on your end right?

**Comment by gyretech** [comment]
I will submit a PR for this today.

- Keshwar

________________________________

**Comment by tidyui** [comment]
Moved to `8.0` as we will implement a completely new routing middleware for this major version
