### ISSUE TITLE
Getting archive by tag crashes in 7.0.1

### ISSUE THREAD

**Issue by morkonom** [PiranhaCMS/piranha.core#801]
We ran a stage site for a new customer on Piranha 6.1. Now after upgrading to 7.0 an error occurs when getting archive posts by tag or category.

`blog.Archive = await _api.Archives.GetByIdAsync(blog.Id, page, category, tag, year, month);`
In the above example the blog.Id is set (and the blog object has been previously loaded without any problem), the page is set to "1" and the category is set to a Guid that is confirmed to exist in the database. Tag, year and month are all null.

Running this code with both tag and category set to null works fine. Setting any of those will produce these errors. Category set:
```
Object reference not set to an instance of an object.
   at Piranha.Services.PostService.GetCategoryByIdAsync(Guid id)
   at Piranha.Services.ArchiveService.GetByIdAsync[T](Guid archiveId, Nullable`1 currentPage, Nullable`1 categoryId, Nullable`1 tagId, Nullable`1 year, Nullable`1 month, Nullable`1 pageSize)
```

and if the tag is set:
```
Object reference not set to an instance of an object.
   at Piranha.Services.PostService.GetTagByIdAsync(Guid id)
   at Piranha.Services.ArchiveService.GetByIdAsync[T](Guid archiveId, Nullable`1 currentPage, Nullable`1 categoryId, Nullable`1 tagId, Nullable`1 year, Nullable`1 month, Nullable`1 pageSize)
```
I tried adding a new post with new tags and category after the upgrade, to see if it had something to do with bad backwards compatiblity but it produced the same errors.

**Comment by tidyui** [comment]
We have just noticed this behavior as well. However we are only able to reproduce it when running on `SQLite` in our production environments running on `SQLServer` the error does not occur. To help us pinpoint the issue, what database have you tested your application on?

**Comment by tidyui** [comment]
I have kind of located the error and why it wasn't found. When running `App.CacheLevel = Piranha.Cache.CacheLevel.Full` the error does not occur. Since all of our production environments had this setting enabled we mistook it for being database-related. 

We will try to locate the error within the services handling the caching, but for now you can try to enable **full** caching. This means the application will use more memory but unless you have a really big site structure it shouldn't be an issue.

Best regards

**Comment by morkonom** [comment]
Thanks, I tried it and it works great!
