### ISSUE TITLE
publish ver 6.1.1 to IIS

### ISSUE THREAD

**Issue by haidersafaa** [PiranhaCMS/piranha.core#851]
Hi 
I need to publish ver6.1.1 to IIS what the prerequisites I need to install and if there a tutorial for this process

**Comment by tidyui** [comment]
Piranha CMS depends on nothing other that '.NET Core 2.2` so that same applies as when deploying any `.NET Core` application to `IIS`. For more information on this, please take a look at Microsofts official documentation.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.0

Best regards
