### ISSUE TITLE
Blazor evaluation? 

### ISSUE THREAD

**Issue by jensbrak** [PiranhaCMS/piranha.core#886]
As suggested in a comment in #430 Blazor was going to be evaluated. I am curious, did you evaluate Blazor and what did you conclude? 

While it seem like an interesting and promising thing it does not automatically mean it's useful. Still, it makes sense to look at it. Since I cannot find any obvious traces of Blazor in feature branches I guess it is not being an option at the moment. Or is there a road map I've missed somewhere?

**Comment by tidyui** [comment]
Yes we did evaluate it, but at the time it just wasn’t good enough and we decided to go for VueJs in the manager instead which is the 7.0 manager we have today!

**Comment by bl-beep** [comment]
Hi I am also interested in this. Did you have any specific problems with Blazor for the Manager interface or was it just no ready at the time (meaning a decision today might look different)?

**Comment by tidyui** [comment]
@bl-beep Since we were not interested in running the manager as a client only application we only considered server side Blazor. As I haven't looked at it since we evaluated it I can't really speak for how it performs now, but at a time there were just too much server-side processing going on for handling events and client state making the application not as snappy as it should be. The whole execution model at that time gave me the chills and reminded me too much of using `UpdatePanels` in ASP.NET `WebForms`. The simple conclusion at that time was that there was simply too much abstraction between the code and the actual application to get the result we wanted to achieve. 

Another key point in deciding against it is that we always try to support as many standard development models as possible for manager integration as the idea is that is should be **easy** to use the manager as a base admin template for the rest of your application. This considered, we've now intentionally designed it in a way that you can add standard `Razor Pages` or `MVC` functionality into the manager. All reusable `Vue.js`parts of the manager are written as isolated `Applications` instead of `Components` so that they can be easily invoked with standard vanilla js from regular pages ASP.NET server-side pages.

I hope this clarifies the decision!

Best regards

**Comment by bl-beep** [comment]
Thank you for the clarification. I've been playing around a bit with Custom Blocks and Fields and providing a custom Vue Component has allways thrown me off a bit. But in my case I think I could save me most of that if #820  is implemented. 
Regarding the second point how would I get started with adding MVC or Razor Pages to the manager interface. Using [Partials ](http://piranhacms.org/docs/manager-extensions/partials)?
