### ISSUE TITLE
Query based archive routing

### ISSUE THREAD

**Issue by CrossBound** [PiranhaCMS/piranha.core#976]
I am wanting to be able to retrieve archive posts by using query parameters and not just path parameters. For example, I would like to be able to query for a list of posts like this: `/postpage?year=2020&tag=newtag&page=3` rather than having to say `/postpage/year/2020/tag/newtag/page/3`

Is this currently possible?

**Comment by tidyui** [comment]
Hi there! Since the `ArchiveMiddleware` or `IntegratedMiddleware` rewrites the request to standard query parameters these requests are in fact the same:

~~~
GET /postpage/2018/page/3
GET /postpage?year=2018&page=3
~~~

Take a look at the archive action in the example here:

https://github.com/PiranhaCMS/piranha.core/blob/master/examples/MvcWeb/Controllers/CmsController.cs#L38

The only thing that won't work out of the box is `category` and `tag` as their `Id` is passed on from the middleware instead of the slug, but if you use another parameter name you can take care of this in your code, for example:

~~~
GET /postpage?categoryfilter=mycategory
~~~

Best regards
