### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by mhdmehboobkhan** [PiranhaCMS/piranha.core#981]
Hi i was trying to setup the project after downloading from repository. But when i run the project by VS: 2019 it's giving me this error could you please help me. I don't want to spend time at startup.

![Screenshot_205](https://user-images.githubusercontent.com/19686930/72226505-aa409a00-35b3-11ea-9cad-afd683a4fbac.jpg)

**Comment by tidyui** [comment]
Hi there! The master branch of the repo is our development branch and is not tested like the released versions on NuGet. For starting a new project we recommend using the NuGet packages and creating the project with one of our templates!

Best regards

**Comment by mhdmehboobkhan** [comment]
After trying to add the nuget package i got this error can you please provide me a full detailed starting guide.
![Screenshot_206](https://user-images.githubusercontent.com/19686930/72248306-aabf4c00-3618-11ea-9748-28d3c0743c39.jpg)

Thanks

**Comment by tidyui** [comment]
You can't reference a package with the same name as your project in .NET, thus the cyclic dependency. Please rename you project.

Best regards

**Comment by mhdmehboobkhan** [comment]
Hi,
I want to see all of the code and want to work with the solution. After installing the packages it's just added the references.
Can you please let me know how i can work with code?
![Screenshot_207](https://user-images.githubusercontent.com/19686930/72251263-5d92a880-361f-11ea-89ae-e5d1afe88904.jpg)

Thanks

**Comment by tidyui** [comment]
Packages are always references. If you want to work directly with the source code you should clone the repository like you started doing. The only thing I meant was that the `master` branch is our development branch and is not necessarily stable.

If you want the source code equivalent to the currently release packages you can find them in the branch `version/v8.0`.

Best regards

**Comment by mhdmehboobkhan** [comment]
Thanks that's good i can test with v8.0 and can you please let me know where is the connection string setting file exist in the code.
Or any helping steps after donwload the code which make the process fast because i want to work quickly my client is waiting to see the progress and i don't want to use wordpress.

Thanks

**Comment by tidyui** [comment]
If you're only starting a new web project we have good templates for this (NuGet packages) where you get a running web application in just a matter of seconds. The only reason for cloning and using the source code is if you want to make changes in the core and contribute to the project. If I were unclear on how to start a new project from the templates, please take a look here:

http://piranhacms.org/docs/basics/project-templates

If you want to use source code and use the example projects in the repo as a starting point (not recommended for a regular project) the connection strings are just hard coded into `Startup.cs` because they are intended to be used for testing while developing.

The projects created from the templates have their connection string in `appsettings.json` as usual.
