### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by lnaie** [PiranhaCMS/piranha.core#982]
Hi,

Amazing work guys, lovely! Still in the process of figuring out how it works and how may I use it for my own needs.

- 1st question that popped up is how would I use this to store and retrieve structured data via API endpoints? To use it as storage backend for mobile apps or so, for instance.

- 2nd question would be about multi-tenancy: is it supported and how?

Thanks,
Lucian

**Comment by r4g-jon** [comment]
Hi @lnaie 

I was looking at the multi-tenancy part of Piranha the other day and it is supported. Here's some brief instructions on how I did it which I hope will help you. If you get stuck, let me know and I will try to help. 

I set up this demo on my development laptop, obviously you might need to make some extra changes for running the site on production IIS. I haven't tried this yet on Azure however but I'm hoping to at some point in the near future. Ok, so that is what I did:

**Create a new site type**
I created a new site type (see http://piranhacms.org/docs/content/sites) so that I could add in some fields and regions I wanted. I also thought 

**Update your Windows hosts file**
We want to be able to run the two sites on our local laptops so we are going to add two hostnames which point to your local laptop. Add the two lines to the bottom of your hosts file:
local.mywebsitetest1.com   127.0.0.1
local.mywebsitetest2.com   127.0.0.1

**Publish the Piranha website to a local folder**
In Visual Studio, publish your website to a local folder. In this example, publish it to c:\piranha-website

**Set up IIS**
Now we have the hostnames set up and the site published, we need to set up IIS to be able to browse the sites. 

Open IIS Manager and create a new website called 'piranha'. Set the physical path to c:\piranha-website.  Click ok to create the site. Next, click on "Edit bindings" on the right hand site of IIS Manager and add in local.mywebsitetest1.com as the hostname. Do the same for local.mywebsitetest2.com

You should now be able to browse http://local.mywebsitetest1.com and local.mywebsitetest2.com! This now shows that both sites are pointing to the single Piranha instance.

**Create the two sites in Piranha**
Login to the Piranha admin console and edit click on the "Default website" to edit it and add local.mywebsitetest1.com as the hostname and save it. Create a test page with URL /test and add some content on to show that it's running on local.mywebsitetest1.com. 

Add a new site in Piranha admin and add local.mywebsitetest2.com as the hostname.  Again, create a test page with some content on and make sure the URL is /test.

9. You should now be able to go to http://local.mywebsitetest1.com/test and http://local.mywebsitetest2.com/test you should see different content. This shows that one Piranha instance has the two sites running 

I hope this helps!

**Comment by tidyui** [comment]
Like @r4g-jon has describe above Piranha has support for multiple sites. There are however a couple of features that would need to be added for multi-tenancy support in the manager.

* Possibility to restrict Content Types per Site
* Possibility to restrict Users per Site
* Possibility for different media-libraries per Site

At the moment all of these things are application wide. The current site support was never intended to be used as a true multi-tenant solution, but rather a way to publish several sites sharing admins and content between them, for example if you have a main site but want to publish a couple of marketing sites for specific products or services.

**Comment by tidyui** [comment]
I just realized there's already an issue for this with detail information here #806.

Best regards

**Comment by muffadalis** [comment]
Hi, 
I realise that this is a duplicate issue but I feel this more contextually appropriate place to ask this question here. I have a multi-tenant app and I override the `OnModelCreating` method to add TenantCode like so,

`            mb.Property<string>("TenantCode").IsRequired();
            mb.HasQueryFilter(x => EF.Property<string>(x, "TenantCode") == tenant.Code);
`

Is there a way to achieve this? I see that `Piranha.Data.EF.SQLServer.SQLServerDb` is sealed?

Thanks.
