### ISSUE TITLE
adding another site (culture)

### ISSUE THREAD

**Issue by ulfetalhussaini** [PiranhaCMS/piranha.core#983]
hi, when iam adding a new site with another culture can't review pages that site.

![culture_LI](https://user-images.githubusercontent.com/38277711/72441893-7f756200-37bc-11ea-8fc0-642d162d9d77.jpg)

**Comment by tidyui** [comment]
Hi there @ulfetalhussaini! This has always been an issue since the first version of Piranha in 2011. The problem is that we don't have any way of knowing how we should access the different sites, we can't even be sure that the same web application should consume the data from the different sites.

We have a number of suggestions on how to amend this, all of them includes changing how sites work. The suggestion that we're leaning towards is splitting it into two logical objects, `Applications` and `Sites` where `Applications` would hold the domain-names for the application and Sites would hold the `slug`. This feature is tracked in the issues #806 and #461.

What we normally have done is this: 

1. Add different hostnames for your sites
2. Log into the manager using the hostname you want to manage/preview.

Since you're already on the domain that you've specified the correct site will then be resolved and you will be able to preview.
